import {useState} from "react";
import {CalendarDays,ChevronLeft,ChevronRight,CirclePlus,Download} from "lucide-react";
import {api} from "../../api";
import type {StudyPlan,Subject,Task,Topic} from "../../types";
import {GoogleEventLink} from "./StudyHub";

const key=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;

export function CalendarView({tasks,subjects,topics,plans,timeZone,openTask,addTaskOnDate,moveTask,openPlan}:{tasks:Task[];subjects:Subject[];topics:Topic[];plans:StudyPlan[];timeZone:string;openTask:(task:Task)=>void;addTaskOnDate:(date:string)=>void;moveTask:(task:Task,date:string)=>Promise<void>;openPlan:()=>void}){
  const now=new Date();const [month,setMonth]=useState(new Date(now.getFullYear(),now.getMonth(),1));const [selected,setSelected]=useState(key(now));const [error,setError]=useState("");
  const firstOffset=(month.getDay()+6)%7;const daysInMonth=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
  const cells=Array.from({length:firstOffset+daysInMonth},(_,i)=>i<firstOffset?null:i-firstOffset+1);
  const dateFor=(day:number)=>key(new Date(month.getFullYear(),month.getMonth(),day));
  const planDays=plans.flatMap(plan=>plan.days.filter(day=>!day.calendar_task_uid||!day.scheduled_time).map(day=>({plan,day})));
  const selectedTasks=tasks.filter(task=>task.deadline&&key(new Date(task.deadline))===selected);
  const selectedPlans=planDays.filter(item=>item.day.scheduled_date===selected);
  const selectedExams=subjects.filter(subject=>subject.exam_date===selected);
  const planTaskIds=new Set(plans.flatMap(plan=>plan.days.map(day=>day.calendar_task_uid).filter(Boolean)));
  const unscheduled=tasks.filter(task=>!task.is_done&&!task.deadline&&!planTaskIds.has(task.task_uid));
  function changeMonth(offset:number){const date=new Date(month.getFullYear(),month.getMonth()+offset,1);setMonth(date);setSelected(key(date))}
  async function drop(event:React.DragEvent,date:string){event.preventDefault();const id=event.dataTransfer.getData("text/studyflow-task");const task=tasks.find(item=>item.task_uid===id);if(!task)return;setError("");try{await moveTask(task,date)}catch(err){setError(err instanceof Error?err.message:"Nie udało się przesunąć zadania.")}}
  return <section className="calendar-view view-enter"><div className="calendar-toolbar"><div><span className="kicker">KALENDARZ NAUKI</span><p>Zadania możesz przeciągać między dniami. Dni planu widzisz tutaj automatycznie.</p></div><div className="calendar-export-actions"><button className="secondary" onClick={()=>void api.exportCalendar().catch(err=>setError(err instanceof Error?err.message:"Nie udało się pobrać kalendarza."))}><Download size={16}/>Eksport .ics</button><button className="primary" onClick={()=>addTaskOnDate(selected)}><CirclePlus/>Dodaj zadanie</button></div></div>{error&&<p className="form-error">{error}</p>}
    <div className="big-calendar panel"><div className="big-calendar-head"><button className="icon" onClick={()=>changeMonth(-1)}><ChevronLeft/></button><h2>{new Intl.DateTimeFormat("pl-PL",{month:"long",year:"numeric"}).format(month)}</h2><button className="icon" onClick={()=>changeMonth(1)}><ChevronRight/></button></div>
      <div className="big-calendar-grid">{["Pon","Wt","Śr","Czw","Pt","Sob","Nie"].map(day=><strong key={day}>{day}</strong>)}{cells.map((number,index)=>{if(!number)return <div className="calendar-day blank" key={index}/>;const date=dateFor(number);const dayTasks=tasks.filter(task=>task.deadline&&key(new Date(task.deadline))===date);const dayPlans=planDays.filter(item=>item.day.scheduled_date===date);const exams=subjects.filter(subject=>subject.exam_date===date);return <div key={index} className={`calendar-day${date===key(now)?" today":""}${selected===date?" selected":""}`} onClick={()=>setSelected(date)} onDragOver={event=>event.preventDefault()} onDrop={event=>void drop(event,date)}><span>{number}</span>{exams.slice(0,1).map(subject=><i className="calendar-event exam" key={subject.subject_uid}>Egzamin · {subject.name}</i>)}{dayPlans.slice(0,2).map(({day})=><button key={day.day_uid} className="calendar-event plan" onClick={event=>{event.stopPropagation();openPlan()}}>Plan · {day.title}</button>)}{dayTasks.slice(0,2).map(task=><button key={task.task_uid} draggable onDragStart={event=>event.dataTransfer.setData("text/studyflow-task",task.task_uid)} className={`calendar-event ${task.priority.toLowerCase()}`} onClick={event=>{event.stopPropagation();openTask(task)}}>{task.title}</button>)}{exams.length+dayPlans.length+dayTasks.length>5&&<small className="event-more">+{exams.length+dayPlans.length+dayTasks.length-5} więcej</small>}</div>})}</div>
      <div className="main-calendar-details"><div className="main-calendar-details-head"><div><span className="kicker">WYBRANY DZIEŃ</span><h3>{new Intl.DateTimeFormat("pl-PL",{dateStyle:"full"}).format(new Date(`${selected}T12:00`))}</h3></div><button className="primary compact" onClick={()=>addTaskOnDate(selected)}><CirclePlus/>Dodaj zadanie</button></div>
        {!selectedTasks.length&&!selectedPlans.length&&!selectedExams.length?<div className="calendar-empty-day"><CalendarDays/><p>Ten dzień jest wolny.</p></div>:<div className="main-day-events">{selectedPlans.map(({plan,day})=><article key={day.day_uid}><span className="agenda-date plan"><CalendarDays/></span><div><strong>{day.title}</strong><small>{plan.title} · {day.scheduled_time?day.scheduled_time+" · ":""}{day.duration_minutes} min {day.is_done?"· ukończone":""}</small><p>{day.objective}</p><GoogleEventLink title={`Nauka: ${day.title}`} date={day.scheduled_date} time={day.scheduled_time} duration={day.duration_minutes} timeZone={timeZone} details={day.objective}/></div></article>)}{selectedTasks.map(task=><article key={task.task_uid}><button onClick={()=>openTask(task)}><strong>{task.title}</strong><small>{topics.find(topic=>topic.topic_uid===task.topic_uid)?.name} · {new Intl.DateTimeFormat("pl-PL",{hour:"2-digit",minute:"2-digit"}).format(new Date(task.deadline!))}</small></button><GoogleEventLink title={task.title} date={selected} details={task.notes??""}/></article>)}{selectedExams.map(subject=><article key={subject.subject_uid} className="exam-detail" style={{"--subject-color":subject.color} as React.CSSProperties}><strong>Egzamin: {subject.name}</strong><GoogleEventLink title={`Egzamin: ${subject.name}`} date={selected} details="Termin egzaminu"/></article>)}</div>}
      </div></div>{unscheduled.length>0&&<div className="calendar-unscheduled panel"><h3>Zadania bez terminu</h3><p>Przeciągnij zadanie na dzień w kalendarzu.</p><div>{unscheduled.slice(0,30).map(task=><button key={task.task_uid} draggable onDragStart={event=>event.dataTransfer.setData("text/studyflow-task",task.task_uid)}>{task.title}</button>)}</div></div>}</section>;
}
