import {useEffect,useState} from "react";
import {CalendarDays,ChevronDown,ChevronLeft,ChevronRight,Clock3} from "lucide-react";

export function DatePicker({ name, defaultValue = "", withTime = false, onChange }: { name: string; defaultValue?: string; withTime?: boolean; onChange?: (value:string)=>void }) {
  const initialDate = defaultValue ? new Date(/^\d{4}-\d{2}-\d{2}$/.test(defaultValue)?`${defaultValue}T12:00`:defaultValue) : null; const [selected, setSelected] = useState<Date|null>(initialDate && !Number.isNaN(initialDate.getTime()) ? initialDate : null); const [month, setMonth] = useState(new Date(initialDate?.getFullYear() ?? new Date().getFullYear(), initialDate?.getMonth() ?? new Date().getMonth(), 1)); const [open,setOpen]=useState(false); const [time,setTime]=useState(initialDate&&withTime?`${String(initialDate.getHours()).padStart(2,"0")}:${String(initialDate.getMinutes()).padStart(2,"0")}`:"12:00");
  useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.stopImmediatePropagation();setOpen(false)}};document.addEventListener("keydown",escape,true);return()=>document.removeEventListener("keydown",escape,true)},[open]);
  const firstOffset=(month.getDay()+6)%7; const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); const days=Array.from({length:firstOffset+count},(_,i)=>i<firstOffset?null:i-firstOffset+1);
  const pad=(n:number)=>String(n).padStart(2,"0"); const dateValue=selected?`${selected.getFullYear()}-${pad(selected.getMonth()+1)}-${pad(selected.getDate())}`:""; const value=dateValue&&withTime?`${dateValue}T${time}`:dateValue;
  const label=selected?new Intl.DateTimeFormat("pl-PL",{day:"numeric",month:"long",year:"numeric"}).format(selected)+(withTime?` · ${time}`:""):"Wybierz datę";
  return <div className={open?"date-picker open":"date-picker"}><input type="hidden" name={name} value={value}/><button type="button" className="date-trigger" onClick={()=>setOpen(!open)}><CalendarDays/><span className={selected?"":"placeholder"}>{label}</span><ChevronDown/></button>{open&&<div className="calendar-popover"><div className="calendar-head"><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><strong>{new Intl.DateTimeFormat("pl-PL",{month:"long",year:"numeric"}).format(month)}</strong><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div><div className="calendar-grid">{["Pn","Wt","Śr","Cz","Pt","Sb","Nd"].map(day=><small key={day}>{day}</small>)}{days.map((day,index)=>day?<button type="button" key={index} className={selected?.getFullYear()===month.getFullYear()&&selected?.getMonth()===month.getMonth()&&selected?.getDate()===day?"selected":""} onClick={()=>{setSelected(new Date(month.getFullYear(),month.getMonth(),day));onChange?.(`${month.getFullYear()}-${pad(month.getMonth()+1)}-${pad(day)}`);if(!withTime)setOpen(false);}}>{day}</button>:<i key={index}/>)}</div>{withTime&&<div className="time-row"><Clock3/><span>Godzina</span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/><button type="button" className="calendar-done" disabled={!selected} onClick={()=>setOpen(false)}>Gotowe</button></div>}<button type="button" className="clear-date" onClick={()=>{setSelected(null);onChange?.("");setOpen(false);}}>Wyczyść termin</button></div>}</div>;
}
