import {useState} from "react";
import {Archive,CalendarDays,ChevronRight,CirclePlus,Pencil,RotateCcw,Trash2} from "lucide-react";
import {api} from "../../api";
import type {Subject,Topic} from "../../types";

export function SubjectsView({subjects,archived,topics,add,edit,remove,openTopics,onChanged}:{subjects:Subject[];archived:Subject[];topics:Topic[];add:()=>void;edit:(subject:Subject)=>void;remove:(subject:Subject)=>void;openTopics:(subject:Subject,topic?:Topic)=>void;onChanged:()=>Promise<void>}){
  const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
  async function archive(subject:Subject,value:boolean){setBusy(subject.subject_uid);setError("");try{await api.updateSubject(subject.subject_uid,{archived:value});await onChanged()}catch(err){setError(err instanceof Error?err.message:"Nie udało się zmienić statusu przedmiotu.")}finally{setBusy(null)}}
  return <section className="subject-view view-enter"><div className="section-toolbar"><p>Przedmioty, tematy i cele w jednym miejscu.</p><button className="secondary" onClick={add}><CirclePlus/>Dodaj przedmiot</button></div>{error&&<p className="form-error">{error}</p>}
    {!subjects.length?<div className="onboarding"><CirclePlus/><h2>Dodaj pierwszy przedmiot</h2><p>Potem dodasz tematy i plan nauki.</p><button className="primary" onClick={add}>Dodaj przedmiot</button></div>:<div className="subject-grid">{subjects.map(subject=>{const own=topics.filter(topic=>topic.subject_uid===subject.subject_uid);return <article className="subject-card" key={subject.subject_uid} style={{"--subject-color":subject.color} as React.CSSProperties}><div className="card-top"><span className="subject-letter large" style={{background:subject.color}}>{subject.name[0]}</span><div className="subject-card-actions"><button className="icon" title="Edytuj przedmiot" onClick={()=>edit(subject)}><Pencil/></button><button className="icon" title="Archiwizuj przedmiot" disabled={busy===subject.subject_uid} onClick={()=>void archive(subject,true)}><Archive/></button><button className="icon topic-delete" title="Usuń przedmiot" onClick={()=>remove(subject)}><Trash2/></button></div></div><button className="subject-name-link" onClick={()=>openTopics(subject)}><h3>{subject.name}</h3><ChevronRight/></button><p><CalendarDays/> {subject.exam_date??"Bez daty egzaminu"}</p><div className="subject-tags">{subject.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="topic-progress"><span><b>{own.filter(topic=>topic.is_done).length}</b> z {own.length} tematów</span><div><i style={{width:`${own.length?own.filter(topic=>topic.is_done).length/own.length*100:0}%`,background:subject.color}}/></div></div>{own.slice(0,3).map(topic=><button className="topic-chip" key={topic.topic_uid} onClick={()=>openTopics(subject,topic)}>{topic.name}<ChevronRight/></button>)}</article>})}<button className="add-card" onClick={add}><CirclePlus/><strong>Nowy przedmiot</strong><span>Zacznij kolejny kierunek</span></button></div>}
    {archived.length>0&&<details className="archived-subjects"><summary>Archiwum przedmiotów ({archived.length})</summary><div>{archived.map(subject=><article key={subject.subject_uid} style={{"--subject-color":subject.color} as React.CSSProperties}><span className="subject-letter" style={{background:subject.color}}>{subject.name[0]}</span><strong>{subject.name}</strong><button className="secondary compact" disabled={busy===subject.subject_uid} onClick={()=>void archive(subject,false)}><RotateCcw size={15}/>Przywróć</button><button className="icon topic-delete" title="Usuń przedmiot z archiwum" onClick={()=>remove(subject)}><Trash2/></button></article>)}</div></details>}
  </section>;
}
