import { t } from "../../i18n";
import {useState} from "react";
import {Archive,CalendarDays,ChevronRight,CirclePlus,Pencil,RotateCcw,Trash2} from "lucide-react";
import {api} from "../../api";
import type {Subject,Topic} from "../../types";

export function SubjectsView({subjects,archived,topics,add,edit,remove,openTopics,onChanged}:{subjects:Subject[];archived:Subject[];topics:Topic[];add:()=>void;edit:(subject:Subject)=>void;remove:(subject:Subject)=>void;openTopics:(subject:Subject,topic?:Topic)=>void;onChanged:()=>Promise<void>}){
  const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState("");
  async function archive(subject:Subject,value:boolean){setBusy(subject.subject_uid);setError("");try{await api.updateSubject(subject.subject_uid,{archived:value});await onChanged()}catch(err){setError(err instanceof Error?err.message:t("Failed to change subject status."))}finally{setBusy(null)}}
  return <section className="subject-view view-enter"><div className="section-toolbar"><p>{t("Subjects, topics, and goals in one place.")}</p><button className="secondary" onClick={add}><CirclePlus/>{t("Add subject")}</button></div>{error&&<p className="form-error">{error}</p>}
    {!subjects.length?<div className="onboarding"><CirclePlus/><h2>{t("Add first subject")}</h2><p>{t("You will add topics and a study plan later.")}</p><button className="primary" onClick={add}>{t("Add subject")}</button></div>:<div className="subject-grid">{subjects.map(subject=>{const own=topics.filter(topic=>topic.subject_uid===subject.subject_uid);return <article className="subject-card" key={subject.subject_uid} style={{"--subject-color":subject.color} as React.CSSProperties}><div className="card-top"><span className="subject-letter large" style={{background:subject.color}}>{subject.name[0]}</span><div className="subject-card-actions"><button className="icon" title={t("Edit subject")} onClick={()=>edit(subject)}><Pencil/></button><button className="icon" title={t("Archive subject")} disabled={busy===subject.subject_uid} onClick={()=>void archive(subject,true)}><Archive/></button><button className="icon topic-delete" title={t("Delete subject")} onClick={()=>remove(subject)}><Trash2/></button></div></div><button className="subject-name-link" onClick={()=>openTopics(subject)}><h3>{subject.name}</h3><ChevronRight/></button><p><CalendarDays/> {subject.exam_date??t("No exam date")}</p><div className="subject-tags">{subject.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="topic-progress"><span><b>{own.filter(topic=>topic.is_done).length}</b> {t("from")}{own.length} {t("topics")}</span><div><i style={{width:`${own.length?own.filter(topic=>topic.is_done).length/own.length*100:0}%`,background:subject.color}}/></div></div>{own.slice(0,3).map(topic=><button className="topic-chip" key={topic.topic_uid} onClick={()=>openTopics(subject,topic)}>{topic.name}<ChevronRight/></button>)}</article>})}<button className="add-card" onClick={add}><CirclePlus/><strong>{t("New subject")}</strong><span>{t("Start another course of study")}</span></button></div>}
    {archived.length>0&&<details className="archived-subjects"><summary>{t("Subject archive (")}{archived.length})</summary><div>{archived.map(subject=><article key={subject.subject_uid} style={{"--subject-color":subject.color} as React.CSSProperties}><span className="subject-letter" style={{background:subject.color}}>{subject.name[0]}</span><strong>{subject.name}</strong><button className="secondary compact" disabled={busy===subject.subject_uid} onClick={()=>void archive(subject,false)}><RotateCcw size={15}/>{t("Restore")}</button><button className="icon topic-delete" title={t("Delete subject from archive")} onClick={()=>remove(subject)}><Trash2/></button></article>)}</div></details>}
  </section>;
}
