import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CirclePlus, Clock3, Copy, HelpCircle, History, ImagePlus, Keyboard, Layers3, LayoutDashboard, ListTodo, LogOut, Menu, Mic, MicOff, Moon, MoreHorizontal, Pencil, Play, Search, Send, Settings, ShieldCheck, Sparkles, Sun, Trash2, X } from "lucide-react";
import { api, clearToken, hasToken, setToken } from "./api";
import type { AiConversation, AiMaterial, GeneratedNotes, GeneratedStudyPlan, Review, Session, StudyPlan, Subject, T3achProposal, Task, Topic, User } from "./types";
import {StudyHub,PlanBoard} from "./features/study/StudyHub";
import {CalendarView as StudyCalendarView} from "./features/study/CalendarView";
import {FirstRunWizard} from "./features/study/FirstRunWizard";
import {DatePicker} from "./features/study/DatePicker";
import {TimezoneField} from "./features/study/TimezoneField";
import {SubjectsView} from "./features/study/SubjectsView";
import {AiAssistantV2,VoiceT3ach,type T3achMemory} from "./features/ai/Assistant";
import {AiHistoryModalV2,TaskAiMaterials} from "./features/ai/Materials";
import {matchesShortcut,shortcutFromKey} from "./shortcut";

type View = "overview" | "subjects" | "topics" | "tasks" | "calendar" | "sessions" | "topic-detail" | "task-detail" | "session-detail";
type Modal = "subject" | "topic" | "task" | "session" | null;
type EditTarget = { kind: "subject"; value: Subject } | { kind: "topic"; value: Topic } | { kind: "task"; value: Task };
type DeleteTarget = { kind: "subject" | "topic" | "task" | "session"; id: string; name: string };
type Accent = string;
const GUIDED_TOUR_STEPS = 11;

const fmtDate = (value: string | null) => value ? new Intl.DateTimeFormat("pl-PL", { day: "numeric", month: "short" }).format(new Date(/^\d{4}-\d{2}-\d{2}$/.test(value)?`${value}T12:00`:value)) : "Bez terminu";
const initials = (name: string) => name.slice(0, 2).toUpperCase();
const localDay = (date: Date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
function studyStreak(sessions: Session[]) { const days=new Set(sessions.map(s=>localDay(new Date(s.started_at)))); let cursor=new Date(); if(!days.has(localDay(cursor))) cursor.setDate(cursor.getDate()-1); let count=0; while(days.has(localDay(cursor))){count++;cursor.setDate(cursor.getDate()-1)} return count; }

function Brand({onHome}:{onHome?:()=>void}) {
  return <button type="button" className="brand" onClick={onHome}><span className="brand-mark"><Sparkles size={18} /></span><span>studyflow<span className="dot">.</span></span></button>;
}

function AccentPicker({value,change,className=""}:{value:Accent;change:(accent:Accent)=>void;className?:string}) {
  const accents:{id:Accent;label:string;color:string}[]=[{id:"lime",label:"Limonkowy",color:"#c8f05a"},{id:"violet",label:"Fioletowy",color:"#a78bfa"},{id:"pink",label:"Różowy",color:"#f472b6"},{id:"blue",label:"Niebieski",color:"#60a5fa"},{id:"graphite",label:"Grafitowy",color:"#94a3b8"}];
  const [open,setOpen]=useState(false);const selected=accents.find(accent=>accent.id===value);const selectedColor=selected?.color??(value.startsWith("#")?value:"#c8f05a");
  function selectAccent(accent:Accent){document.documentElement.classList.add("accent-changing");change(accent);window.setTimeout(()=>document.documentElement.classList.remove("accent-changing"),520);window.setTimeout(()=>setOpen(false),160)}
  return <section className={`accent-picker ${open?"open":""} ${className}`}><button type="button" className="accent-picker-trigger" onClick={()=>setOpen(current=>!current)} aria-expanded={open}><i style={{"--swatch":selectedColor} as React.CSSProperties}/><span>Kolor motywu</span><ChevronDown/></button><div className="accent-picker-options" aria-hidden={!open}>{accents.map(accent=><button type="button" key={accent.id} className={value===accent.id?"active":""} style={{"--swatch":accent.color} as React.CSSProperties} onClick={()=>selectAccent(accent.id)} title={accent.label} aria-label={`Motyw ${accent.label}`} tabIndex={open?0:-1}><i/>{value===accent.id&&<Check/>}</button>)}<label className={!selected?"custom-accent active":"custom-accent"} title="Własny kolor"><input type="color" value={selectedColor} onChange={event=>selectAccent(event.target.value)} tabIndex={open?0:-1}/><span style={{"--swatch":selectedColor} as React.CSSProperties}/><Sparkles/></label></div></section>
}

function SubjectColorField({initial}:{initial:string}){
  const [color,setColor]=useState(initial);
  return <label>Kolor przedmiotu<div className="subject-color-field"><input type="color" name="color" value={color} onChange={event=>setColor(event.target.value)} aria-label="Wybierz kolor przedmiotu"/><span className="subject-color-preview" style={{background:color}}/><strong>{color.toUpperCase()}</strong></div><small className="field-hint">Wybrany kolor pojawi się na przedmiocie, tematach i w kalendarzu.</small></label>;
}

type SelectOption = { value: string; label: string };
function SelectField({ name, options, defaultValue, required, onChange }: { name: string; options: SelectOption[]; defaultValue?: string; required?: boolean; onChange?: (value:string)=>void }) {
  const initial = defaultValue ?? options[0]?.value ?? ""; const [value, setValue] = useState(initial); const [open, setOpen] = useState(false);
  useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key==="Escape"){event.stopImmediatePropagation();setOpen(false)}};document.addEventListener("keydown",escape,true);return()=>document.removeEventListener("keydown",escape,true)},[open]);
  const selected = options.find(option => option.value === value);
  return <div className={open ? "custom-select open" : "custom-select"}><input type="hidden" name={name} value={value} required={required}/><button type="button" className="select-trigger" onClick={()=>setOpen(!open)}><span>{selected?.label ?? "Wybierz…"}</span><ChevronDown /></button>{open&&<div className="select-options">{options.map(option=><button type="button" className={option.value===value?"selected":""} key={option.value} onClick={()=>{setValue(option.value);onChange?.(option.value);setOpen(false);}}><span>{option.label}</span>{option.value===value&&<Check />}</button>)}</div>}</div>;
}


function Auth({ onReady }: { onReady: (newAccount:boolean) => void }) {
  const [register, setRegister] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setError("");
    const data = new FormData(e.currentTarget);
    const username = String(data.get("username")); const password = String(data.get("password"));
    if(register&&password!==String(data.get("confirm_password"))){setError("Hasła muszą być identyczne.");return}
    setBusy(true);
    try {
      if (register) await api.register(username, String(data.get("email")), password);
      const result = await api.login(username, password); setToken(result.access_token); onReady(register);
    } catch (err) { setError(err instanceof Error ? err.message : "Nie udało się zalogować."); }
    finally { setBusy(false); }
  }
  return <main className="auth-page">
    <div className="orb orb-one" /><div className="orb orb-two" />
    <section className="auth-story">
      <Brand />
      <div><span className="eyebrow"><span /> Twój spokojny system nauki</span><h1>Mniej chaosu.<br /><em>Więcej postępu.</em></h1><p>Zamień ambitne plany w małe, konkretne kroki. StudyFlow pomaga skupić się na tym, co naprawdę ważne.</p></div>
      <div className="quote"><div className="avatars"><span>MK</span><span>AN</span><span>+2k</span></div><p>Dołącz do osób, które uczą się mądrzej, nie dłużej.</p></div>
    </section>
    <section className="auth-panel">
      <form className="auth-card" onSubmit={submit}>
        <div className="mobile-brand"><Brand /></div>
        <p className="kicker">Witaj {register ? "w StudyFlow" : "ponownie"}</p>
        <h2>{register ? "Utwórz konto" : "Gotowy na kolejny krok?"}</h2>
        <p className="muted">{register ? "Zacznij porządkować naukę już dziś." : "Zaloguj się i kontynuuj swój plan."}</p>
        <label>Nazwa użytkownika<input name="username" minLength={2} required placeholder="np. Mateusz" autoComplete="username" /></label>
        {register && <label>E-mail <span className="optional">opcjonalnie</span><input name="email" type="email" placeholder="ty@email.pl" autoComplete="email" /></label>}
        <label>Hasło<input name="password" type="password" minLength={8} required placeholder="Minimum 8 znaków" autoComplete={register ? "new-password" : "current-password"} /></label>
        {register&&<label>Potwierdź hasło<input name="confirm_password" type="password" minLength={8} required placeholder="Wpisz hasło ponownie" autoComplete="new-password" /></label>}
        {error && <p className="form-error styled-error"><X />{error}</p>}
        <button className="primary wide" disabled={busy}>{busy ? <span className="loader" /> : <>{register ? "Załóż konto" : "Wejdź do aplikacji"}<ArrowRight size={18} /></>}</button>
        <p className="switch">{register ? "Masz już konto?" : "Nie masz jeszcze konta?"} <button type="button" onClick={() => { setRegister(!register); setError(""); }}>{register ? "Zaloguj się" : "Utwórz je"}</button></p>
      </form>
    </section>
  </main>;
}

function TaskSessionsOverview({sessions,openSession,addSession}:{sessions:Session[];openSession:(session:Session)=>void;addSession:()=>void}) {
  return <section className="panel task-sessions-overview"><div className="panel-head"><div><span className="kicker">POWIĄZANA NAUKA</span><h3>Sesje tego zadania</h3></div><div className="related-session-actions"><strong>{sessions.length}</strong><button className="primary compact" onClick={addSession}><CirclePlus/>Dodaj sesję</button></div></div>{sessions.length?<div className="task-session-cards">{sessions.map(session=><button key={session.study_uid} onClick={()=>openSession(session)}><span className="session-date"><b>{new Date(session.started_at).getDate()}</b><small>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(session.started_at))}</small></span><div><h4>{session.title}</h4><small>{session.duration_minutes??0} min nauki</small><p>{session.notes||"Bez notatki"}</p></div><ChevronRight/></button>)}</div>:<Empty text="Do tego zadania nie przypisano jeszcze sesji nauki."/>}</section>
}

function SessionDetailV2({session,subjects,topics,tasks,edit}:{session:Session;subjects:Subject[];topics:Topic[];tasks:Task[];edit:()=>void}) {const subject=subjects.find(item=>item.subject_uid===session.subject_uid);const topic=topics.find(item=>item.topic_uid===session.topic_uid);const task=tasks.find(item=>item.task_uid===session.task_uid);return <section className="detail-page view-enter"><div className="detail-hero session-detail-hero"><span className="kicker">SESJA NAUKI</span><h2>{session.title}</h2><p>{new Intl.DateTimeFormat("pl-PL",{dateStyle:"full",timeStyle:"short"}).format(new Date(session.started_at))}</p><div><button className="primary" onClick={edit}><Pencil/>Edytuj sesję</button></div></div><div className="detail-grid"><article><Clock3/><small>Czas nauki</small><strong>{session.duration_minutes??0} minut</strong></article><article><BookOpen/><small>Zakres</small><strong>{subject?.name}{topic&&` · ${topic.name}`}{task&&` · ${task.title}`}</strong></article></div><article className="detail-notes"><span className="kicker">NOTATKA Z SESJI</span><p>{session.notes||"Do tej sesji nie dodano notatki."}</p></article></section>}

function SessionAiFields({initialTitle="",initialNotes=""}:{initialTitle?:string;initialNotes?:string}) {
  const [description,setDescription]=useState(""); const [title,setTitle]=useState(initialTitle); const [notes,setNotes]=useState(initialNotes); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function generate(){if(description.trim().length<3)return;setBusy(true);setError("");try{const result=await api.generateSessionNote(description.trim());setTitle(result.title);setNotes(result.notes)}catch(err){setError(err instanceof Error?err.message:"Nie udało się przygotować notatki.")}finally{setBusy(false)}}
  return <div className="session-ai-fields"><label>Tytuł sesji<input name="title" required maxLength={160} value={title} onChange={event=>setTitle(event.target.value)} placeholder="np. Powtórka równań"/></label><label>Co zrobiłeś? <span className="optional">wystarczy kilka słów</span><textarea value={description} onChange={event=>setDescription(event.target.value)} maxLength={1000} placeholder="np. zrobiłem 10 zadań z równań i powtórzyłem wzory"/></label><button type="button" className="session-ai-button" disabled={busy||description.trim().length<3} onClick={generate}>{busy?<span className="loader"/>:<Sparkles/>}{busy?"AI przygotowuje notatkę…":"Utwórz tytuł i notatkę z AI"}</button>{error&&<p className="form-error">{error}</p>}<label>Notatka z sesji<textarea name="notes" value={notes} onChange={event=>setNotes(event.target.value)} rows={6} placeholder="Możesz wpisać notatkę ręcznie lub wygenerować ją powyżej."/></label></div>
}

function ModalForm({ type, subjects, topics, tasks, initialDeadline, initialTask, userId, close, done }: { type: Exclude<Modal, null>; subjects: Subject[]; topics: Topic[]; tasks: Task[]; initialDeadline?:string;initialTask?:Task|null;userId:string;close: () => void; done: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const draftKey=`studyflow_draft_${userId}_${type}`;
  const [draft]=useState<Record<string,string>>(()=>{try{return JSON.parse(localStorage.getItem(draftKey)||"{}") as Record<string,string>}catch{return {}}});
  function saveDraft(event:React.FormEvent<HTMLFormElement>){const target=event.target as HTMLInputElement|HTMLTextAreaElement;if(!target.name||target.type==="password")return;let current:Record<string,string>={};try{current=JSON.parse(localStorage.getItem(draftKey)||"{}") as Record<string,string>}catch{}localStorage.setItem(draftKey,JSON.stringify({...current,[target.name]:target.value}))}
  const initialTopic=initialTask?topics.find(topic=>topic.topic_uid===initialTask.topic_uid):undefined;const [sessionSubject, setSessionSubject] = useState(initialTopic?.subject_uid??subjects[0]?.subject_uid ?? ""); const [sessionTopic, setSessionTopic] = useState(initialTopic?.topic_uid??"");
  const [taskFormSubject,setTaskFormSubject]=useState(topics[0]?.subject_uid??subjects[0]?.subject_uid??"");
  const title = { subject: "Nowy przedmiot", topic: "Nowy temat", task: "Nowe zadanie", session: "Zapisz sesję" }[type];
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true); setError(""); const f = new FormData(e.currentTarget);
    try {
      if (type === "subject") await api.addSubject({ name: String(f.get("name")), exam_date: String(f.get("date")) || null,color:String(f.get("color")),tags:String(f.get("tags")).split(",").map(value=>value.trim()).filter(Boolean) });
      if (type === "topic") await api.addTopic({ name: String(f.get("name")), subject_uid: String(f.get("subject")), difficulty: String(f.get("difficulty")) });
      if (type === "task") await api.addTask({ title: String(f.get("name")), topic_uid: String(f.get("topic")), deadline: String(f.get("deadline")) ? new Date(String(f.get("deadline"))).toISOString() : null, priority: String(f.get("priority")), notes: String(f.get("notes")) || null });
      if (type === "session") await api.addSession({ title: String(f.get("title")), subject_uid: String(f.get("subject")), topic_uid: String(f.get("topic")) || null, task_uid: String(f.get("task")) || null, duration_minutes: Number(f.get("minutes")), notes: String(f.get("notes")) || null });
      localStorage.removeItem(draftKey);done();
    } catch (err) { setError(err instanceof Error ? err.message : "Nie udało się zapisać."); } finally { setBusy(false); }
  }
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onInput={saveDraft} onMouseDown={e => e.stopPropagation()}><button className="icon close" type="button" onClick={close}><X /></button><span className="kicker">Dodaj do StudyFlow</span><h2>{title}</h2>
    {(type === "subject" || type === "topic" || type === "task") && <label>Nazwa<input name="name" required autoFocus defaultValue={draft.name||""} placeholder={type === "subject" ? "np. Matematyka" : type === "topic" ? "np. Pochodne" : "Co trzeba zrobić?"} /></label>}
    {type === "topic" && <label>Przedmiot<SelectField name="subject" required options={subjects.map(s=>({value:s.subject_uid,label:s.name}))}/></label>}
    {type === "session" && <label>Przedmiot<SelectField name="subject" required defaultValue={sessionSubject} options={subjects.map(s=>({value:s.subject_uid,label:s.name}))} onChange={value=>{setSessionSubject(value);setSessionTopic("");}}/></label>}
    {type === "subject" && <><label>Data egzaminu<DatePicker name="date" defaultValue={draft.date}/><small className="field-hint">Opcjonalnie — pomoże ustalić priorytety.</small></label><SubjectColorField initial={draft.color||"#c8f05a"}/><label>Tagi <span className="optional">oddziel przecinkami</span><input name="tags" defaultValue={draft.tags||""} maxLength={300} placeholder="np. semestr 1, egzamin"/></label></>}
    {type === "topic" && <label>Poziom trudności<SelectField name="difficulty" options={[{value:"Łatwy",label:"Łatwy"},{value:"Średni",label:"Średni"},{value:"Trudny",label:"Trudny"}]}/></label>}
    {type === "task" && <><label>Przedmiot<SelectField name="task-subject" required defaultValue={taskFormSubject} options={subjects.map(subject=>({value:subject.subject_uid,label:subject.name}))} onChange={setTaskFormSubject}/></label><label>Temat<SelectField key={taskFormSubject} name="topic" required options={topics.filter(topic=>topic.subject_uid===taskFormSubject).map(topic=>({value:topic.topic_uid,label:topic.name}))}/><small className="field-hint">Lista zawiera tylko tematy z wybranego przedmiotu.</small></label><div className="field-row"><label>Termin<DatePicker name="deadline" withTime defaultValue={draft.deadline||initialDeadline}/></label><label>Priorytet<SelectField name="priority" defaultValue="MEDIUM" options={[{value:"LOW",label:"Niski"},{value:"MEDIUM",label:"Średni"},{value:"HIGH",label:"Wysoki"}]}/></label></div><label>Notatki<textarea name="notes" defaultValue={draft.notes||""} placeholder="Materiały, zakres lub krótka wskazówka…" /></label></>}
    {type === "session" && <><label>Temat <span className="optional">opcjonalnie</span><SelectField key={sessionSubject} name="topic" defaultValue={sessionTopic} options={[{value:"",label:"Bez konkretnego tematu"},...topics.filter(t=>t.subject_uid===sessionSubject).map(t=>({value:t.topic_uid,label:t.name}))]} onChange={setSessionTopic}/></label><label>Zadanie <span className="optional">opcjonalnie</span><SelectField key={sessionTopic} name="task" defaultValue={initialTask?.task_uid??""} options={[{value:"",label:"Bez konkretnego zadania"},...tasks.filter(t=>t.topic_uid===sessionTopic).map(t=>({value:t.task_uid,label:t.title}))]}/></label><label>Czas w minutach<input name="minutes" type="text" inputMode="numeric" pattern="[1-9][0-9]*" required defaultValue="45" /></label><SessionAiFields/></>}
    {error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={busy || ((type === "topic" || type === "session") && !subjects.length) || (type === "task" && !topics.length)}>{busy ? <span className="loader" /> : "Zapisz"}</button>
  </form></div>;
}

function EditForm({ target, subjects, topics, close, done }: { target: EditTarget; subjects: Subject[]; topics: Topic[]; close: () => void; done: () => void }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const editedTask=target.kind==="task"?target.value:null;const editedTaskTopic=editedTask?topics.find(topic=>topic.topic_uid===editedTask.topic_uid):undefined;const [taskFormSubject,setTaskFormSubject]=useState(editedTaskTopic?.subject_uid??subjects[0]?.subject_uid??"");
  async function submit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault(); setBusy(true); setError(""); const f = new FormData(e.currentTarget);
    try {
      if (target.kind === "subject") await api.updateSubject(target.value.subject_uid, { name: String(f.get("name")), exam_date: String(f.get("date")) || null,color:String(f.get("color")),tags:String(f.get("tags")).split(",").map(value=>value.trim()).filter(Boolean) });
      if (target.kind === "topic") await api.updateTopic(target.value.topic_uid, { name: String(f.get("name")), subject_uid: String(f.get("subject")), difficulty: String(f.get("difficulty")), is_done: f.get("done") === "on" });
      if (target.kind === "task") await api.updateTask(target.value.task_uid, { title: String(f.get("name")), topic_uid: String(f.get("topic")), deadline: String(f.get("deadline")) ? new Date(String(f.get("deadline"))).toISOString() : null, priority: String(f.get("priority")) as Task["priority"], notes: String(f.get("notes")) || null });
      done();
    } catch (err) { setError(err instanceof Error ? err.message : "Nie udało się zapisać zmian."); } finally { setBusy(false); }
  }
  const subject = target.kind === "subject" ? target.value : null;
  const topic = target.kind === "topic" ? target.value : null;
  const task = target.kind === "task" ? target.value : null;
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e => e.stopPropagation()}><button className="icon close" type="button" onClick={close}><X /></button><span className="kicker">EDYCJA</span><h2>{target.kind === "subject" ? "Edytuj przedmiot" : target.kind === "topic" ? "Edytuj temat" : "Edytuj zadanie"}</h2>
    <label>Nazwa<input name="name" required autoFocus defaultValue={task?.title ?? topic?.name ?? subject?.name} /></label>
    {subject && <><label>Data egzaminu<DatePicker name="date" defaultValue={subject.exam_date ?? ""}/><small className="field-hint">Kliknij pole i wybierz dzień z kalendarza.</small></label><SubjectColorField initial={subject.color}/><label>Tagi <span className="optional">oddziel przecinkami</span><input name="tags" defaultValue={subject.tags.join(", ")} maxLength={300}/></label></>}
    {topic && <><label>Przedmiot<SelectField name="subject" defaultValue={topic.subject_uid} options={subjects.map(s=>({value:s.subject_uid,label:s.name}))}/></label><label>Poziom trudności<SelectField name="difficulty" defaultValue={topic.difficulty??""} options={[{value:"",label:"Bez poziomu"},{value:"Łatwy",label:"Łatwy"},{value:"Średni",label:"Średni"},{value:"Trudny",label:"Trudny"}]}/></label><label className="toggle-line"><input name="done" type="checkbox" defaultChecked={topic.is_done} /> Temat ukończony</label></>}
    {task && <><label>Przedmiot<SelectField name="task-subject" defaultValue={taskFormSubject} options={subjects.map(item=>({value:item.subject_uid,label:item.name}))} onChange={setTaskFormSubject}/></label><label>Temat<SelectField key={taskFormSubject} name="topic" defaultValue={topics.some(topicItem=>topicItem.topic_uid===task.topic_uid&&topicItem.subject_uid===taskFormSubject)?task.topic_uid:undefined} options={topics.filter(topicItem=>topicItem.subject_uid===taskFormSubject).map(topicItem=>({value:topicItem.topic_uid,label:topicItem.name}))}/><small className="field-hint">Po zmianie przedmiotu wybierz należący do niego temat.</small></label><div className="field-row"><label>Termin<DatePicker name="deadline" withTime defaultValue={task.deadline??""}/></label><label>Priorytet<SelectField name="priority" defaultValue={task.priority} options={[{value:"LOW",label:"Niski"},{value:"MEDIUM",label:"Średni"},{value:"HIGH",label:"Wysoki"}]}/></label></div><label>Notatki<textarea name="notes" defaultValue={task.notes??""} placeholder="Materiały, zakres lub wskazówki…" /></label></>}
    {error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy ? <span className="loader" /> : "Zapisz zmiany"}</button>
  </form></div>;
}

function ProfileForm({ user, avatar, changeAvatar, close, done, logout }: { user: User; avatar:string|null; changeAvatar:(value:string|null)=>void; close:()=>void; done:()=>void; logout:()=>void }) {
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState(avatar);
  function selectAvatar(file?:File){if(!file)return;if(!file.type.startsWith("image/")){setError("Wybierz plik graficzny.");return}if(file.size>2_000_000){setError("Zdjęcie może mieć maksymalnie 2 MB.");return}const reader=new FileReader();reader.onload=()=>{setPreview(String(reader.result));setError("")};reader.readAsDataURL(file)}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");const data=new FormData(event.currentTarget);const password=String(data.get("password"));if(password&&password!==String(data.get("confirm_password"))){setError("Hasła muszą być identyczne.");return}setBusy(true);try{await api.updateMe({username:String(data.get("username")),email:String(data.get("email"))||null,...(password?{password}:{})});changeAvatar(preview);done()}catch(err){setError(err instanceof Error?err.message:"Nie udało się zapisać konta.")}finally{setBusy(false)}}
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal profile-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><button className="icon close" type="button" onClick={close}><X/></button><span className="kicker">TWOJE KONTO</span><h2>Dane konta</h2><div className="avatar-editor"><span>{preview?<img src={preview} alt="Podgląd zdjęcia profilowego"/>:initials(user.username)}</span><label><ImagePlus/>Wgraj zdjęcie<input type="file" accept="image/*" onChange={event=>selectAvatar(event.target.files?.[0])}/></label>{preview&&<button type="button" onClick={()=>setPreview(null)}>Usuń</button>}</div>
    <label>Nazwa użytkownika<input name="username" minLength={2} required defaultValue={user.username}/></label><label>Adres e-mail<input name="email" type="email" defaultValue={user.email??""}/></label><label>Nowe hasło <span className="optional">pozostaw puste bez zmiany</span><input name="password" type="password" minLength={8} placeholder="Minimum 8 znaków" autoComplete="new-password"/></label><label>Potwierdź nowe hasło<input name="confirm_password" type="password" minLength={8} placeholder="Wpisz nowe hasło ponownie" autoComplete="new-password"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<span className="loader"/>:"Zapisz konto"}</button><button className="logout-action" type="button" onClick={logout}><LogOut/>Wyloguj się</button></form></div>
}

function PreferencesForm({user,close,done}:{user:User;close:()=>void;done:()=>void}){
  const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [minutes,setMinutes]=useState(String(user.preferred_minutes));const [shortcut,setShortcut]=useState(user.task_shortcut);const [aiShortcut,setAiShortcut]=useState(user.ai_shortcut);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const amount=Number(minutes);if(!Number.isInteger(amount)||amount<10||amount>240){setError("Wpisz czas od 10 do 240 minut.");return}if(shortcut&&shortcut===aiShortcut){setError("Skróty zadania i Asystenta AI muszą być różne.");return}setBusy(true);setError("");try{await api.updateMe({timezone:String(new FormData(event.currentTarget).get("timezone")),preferred_minutes:amount,task_shortcut:shortcut,ai_shortcut:aiShortcut});done()}catch(err){setError(err instanceof Error?err.message:"Nie udało się zapisać ustawień.")}finally{setBusy(false)}}
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal profile-modal" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><button className="icon close" type="button" onClick={close}><X/></button><span className="kicker">USTAWIENIA UŻYTKOWNIKA</span><h2>Nauka i skróty</h2><TimezoneField value={user.timezone}/><label>Sugerowany czas nauki na dzień<input name="minutes" type="text" inputMode="numeric" pattern="[0-9]+" value={minutes} onChange={event=>setMinutes(event.target.value.replace(/\D/g,""))} placeholder="np. 45"/><small className="field-hint">To punkt wyjścia dla AI. Każdy dzień planu możesz później ustawić osobno.</small></label><label>Skrót dodawania zadania<input value={shortcut} readOnly onKeyDown={event=>{if(event.key==="Tab")return;event.preventDefault();const value=shortcutFromKey(event);if(value!==null)setShortcut(value)}} placeholder="Kliknij i naciśnij kombinację"/><small className="field-hint">Na Macu możesz użyć ⌘ lub Option. Backspace wyłącza skrót.</small></label><label>Skrót otwierania Asystenta AI (T3ACH)<input value={aiShortcut} readOnly onKeyDown={event=>{if(event.key==="Tab")return;event.preventDefault();const value=shortcutFromKey(event);if(value!==null)setAiShortcut(value)}} placeholder="Kliknij i naciśnij kombinację"/><small className="field-hint">Backspace wyłącza skrót. Użyj innej kombinacji niż do zadania.</small></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<span className="loader"/>:"Zapisz ustawienia"}</button></form></div>
}

function SessionEditForm({session,subjects,topics,tasks,close,done}:{session:Session;subjects:Subject[];topics:Topic[];tasks:Task[];close:()=>void;done:()=>void}) {
  const [subject,setSubject]=useState(session.subject_uid); const [topic,setTopic]=useState(session.topic_uid??""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{await api.updateSession(session.study_uid,{title:String(f.get("title")),subject_uid:String(f.get("subject")),topic_uid:String(f.get("topic"))||null,task_uid:String(f.get("task"))||null,duration_minutes:Number(f.get("minutes")),notes:String(f.get("notes"))||null});done()}catch(err){setError(err instanceof Error?err.message:"Nie udało się zapisać sesji")}finally{setBusy(false)}}
  return <div className="modal-backdrop" onMouseDown={close}><form className="modal session-detail" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button className="icon close" type="button" onClick={close}><X/></button><span className="kicker">{new Intl.DateTimeFormat("pl-PL",{dateStyle:"long",timeStyle:"short"}).format(new Date(session.started_at))}</span><h2>Szczegóły sesji</h2><label>Przedmiot<SelectField name="subject" defaultValue={subject} options={subjects.map(s=>({value:s.subject_uid,label:s.name}))} onChange={v=>{setSubject(v);setTopic("")}}/></label><label>Temat<SelectField name={`session-topic-${subject}`} defaultValue={topic} options={[{value:"",label:"Bez konkretnego tematu"},...topics.filter(t=>t.subject_uid===subject).map(t=>({value:t.topic_uid,label:t.name}))]} onChange={setTopic}/></label><label>Zadanie<SelectField name={`session-task-${topic}`} defaultValue={session.task_uid??""} options={[{value:"",label:"Bez konkretnego zadania"},...tasks.filter(t=>t.topic_uid===topic).map(t=>({value:t.task_uid,label:t.title}))]}/></label><label>Czas nauki w minutach<input name="minutes" type="text" inputMode="numeric" pattern="[1-9][0-9]*" required defaultValue={session.duration_minutes??1}/></label><SessionAiFields initialTitle={session.title} initialNotes={session.notes??""}/>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?<span className="loader"/>:"Zapisz zmiany"}</button></form></div>
}

function App() {
  const [authenticated, setAuthenticated] = useState(hasToken());
  const [user, setUser] = useState<User | null>(null); const [subjects, setSubjects] = useState<Subject[]>([]); const [archivedSubjects,setArchivedSubjects]=useState<Subject[]>([]); const [topics, setTopics] = useState<Topic[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [sessions, setSessions] = useState<Session[]>([]);const [plans,setPlans]=useState<StudyPlan[]>([]);const [reviews,setReviews]=useState<Review[]>([]);
  const [view, setView] = useState<View>("overview"); const [modal, setModal] = useState<Modal>(null); const [editing, setEditing] = useState<EditTarget | null>(null); const [loading, setLoading] = useState(true); const [menu, setMenu] = useState(false); const [search, setSearch] = useState("");
  const [theme, setTheme] = useState<"light" | "dark">(() => localStorage.getItem("studyflow_theme") === "dark" ? "dark" : "light");
  const [accent,setAccent]=useState<Accent>(()=>{const saved=localStorage.getItem("studyflow_accent");return saved&&(["lime","violet","pink","blue","graphite"].includes(saved)||/^#[0-9a-f]{6}$/i.test(saved))?saved:"lime"});
  const [subjectMenu, setSubjectMenu] = useState<string | null>(null);
  const [topicScope, setTopicScope] = useState<string | null>(null); const [focusedTopic, setFocusedTopic] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null); const [deleting, setDeleting] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const [profileOpen,setProfileOpen]=useState(false); const [preferencesOpen,setPreferencesOpen]=useState(false); const [taskSubject,setTaskSubject]=useState(""); const [taskTopic,setTaskTopic]=useState(""); const [taskStatus,setTaskStatus]=useState("open"); const [taskPriority,setTaskPriority]=useState("");const [taskWhen,setTaskWhen]=useState("all");const [bulkMode,setBulkMode]=useState(false);const [selectedTaskIds,setSelectedTaskIds]=useState<Set<string>>(new Set());
  const [settingsOpen,setSettingsOpen]=useState(false); const [avatar,setAvatar]=useState<string|null>(null);
  const [tourStep,setTourStep]=useState(0);
  const [welcome,setWelcome]=useState(false);
  const [sessionEditing,setSessionEditing]=useState<Session|null>(null);
  const [taskDraftDeadline,setTaskDraftDeadline]=useState<string|undefined>();const [sessionDraftTask,setSessionDraftTask]=useState<Task|null>(null);
  const [detailTopic,setDetailTopic]=useState<Topic|null>(null); const [detailTask,setDetailTask]=useState<Task|null>(null); const [detailSession,setDetailSession]=useState<Session|null>(null); const [aiNotesOpen,setAiNotesOpen]=useState(false); const [aiHistoryOpen,setAiHistoryOpen]=useState(false); const [t3achOpen,setT3achOpen]=useState(false); const [t3achMemory,setT3achMemory]=useState<T3achMemory>({turns:[],proposal:null,transcript:"",response:""});
  const [topicStatus,setTopicStatus]=useState("open"); const [topicDifficulty,setTopicDifficulty]=useState("");
  async function load() { setLoading(true); try { const [u,s,a,t,ta,se,p,r] = await Promise.all([api.me(), api.subjects(), api.archivedSubjects(), api.topics(), api.tasks(), api.sessions(), api.plans(), api.reviews()]); const activeIds=new Set(s.items.map(item=>item.subject_uid));const visibleTopics=t.items.filter(item=>activeIds.has(item.subject_uid));const topicIds=new Set(visibleTopics.map(item=>item.topic_uid));setUser(u);setSubjects(s.items);setArchivedSubjects(a.items);setTopics(visibleTopics);setTasks(ta.items.filter(item=>topicIds.has(item.topic_uid)));setDetailTask(current=>current ? ta.items.find(item=>item.task_uid===current.task_uid)??current : null);setSessions(se.items.filter(item=>activeIds.has(item.subject_uid)));setPlans(p.filter(item=>topicIds.has(item.topic_uid)));setReviews(r.filter(item=>topicIds.has(item.topic_uid))); } catch { if (!hasToken()) setAuthenticated(false); } finally { setLoading(false); } }
  useEffect(() => { if (authenticated) load(); }, [authenticated]);
  useEffect(()=>{if(user&&!user.onboarding_complete&&localStorage.getItem(`studyflow_tour_done_${user.user_uid}`)!=="1")setTourStep(1)},[user?.user_uid,user?.onboarding_complete]);
  useEffect(()=>{if(user)setAvatar(localStorage.getItem(`studyflow_avatar_${user.user_uid}`))},[user?.user_uid]);
  useEffect(()=>{if(!settingsOpen)return;const closeSettings=(event:PointerEvent)=>{if(!(event.target as HTMLElement).closest(".profile-settings"))setSettingsOpen(false)};const closeOnEscape=(event:KeyboardEvent)=>{if(event.key==="Escape")setSettingsOpen(false)};document.addEventListener("pointerdown",closeSettings);document.addEventListener("keydown",closeOnEscape);return()=>{document.removeEventListener("pointerdown",closeSettings);document.removeEventListener("keydown",closeOnEscape)}},[settingsOpen]);
  useEffect(()=>{const escape=(event:KeyboardEvent)=>{if(event.key!=="Escape")return;if(t3achOpen)setT3achOpen(false);else if(aiNotesOpen)setAiNotesOpen(false);else if(aiHistoryOpen)setAiHistoryOpen(false);else if(deleteTarget&&!deleting)setDeleteTarget(null);else if(profileOpen)setProfileOpen(false);else if(preferencesOpen)setPreferencesOpen(false);else if(sessionEditing)setSessionEditing(null);else if(editing)setEditing(null);else if(modal)setModal(null);else if(tourStep){localStorage.setItem(`studyflow_tour_done_${user?.user_uid}`,"1");setTourStep(0)}else if(settingsOpen)setSettingsOpen(false);else if(menu)setMenu(false);else return;event.preventDefault()};document.addEventListener("keydown",escape);return()=>document.removeEventListener("keydown",escape)},[t3achOpen,aiNotesOpen,aiHistoryOpen,deleteTarget,deleting,profileOpen,preferencesOpen,sessionEditing,editing,modal,tourStep,settingsOpen,menu]);
  useEffect(()=>{if(!authenticated||(!user?.task_shortcut&&!user?.ai_shortcut))return;
    const handler=(event:KeyboardEvent)=>{if(modal||editing||profileOpen||preferencesOpen||aiNotesOpen||aiHistoryOpen||t3achOpen||deleteTarget||tourStep||!user?.onboarding_complete)return;
      const target=event.target as HTMLElement;if(target.closest("input,textarea,select,[contenteditable=true]"))return;
      if(matchesShortcut(event,user.ai_shortcut)){event.preventDefault();setT3achOpen(true)}
      else if(matchesShortcut(event,user.task_shortcut)){event.preventDefault();startTask()}
    };
    document.addEventListener("keydown",handler);return()=>document.removeEventListener("keydown",handler)
  },[authenticated,user?.task_shortcut,user?.ai_shortcut,user?.onboarding_complete,modal,editing,profileOpen,preferencesOpen,aiNotesOpen,aiHistoryOpen,t3achOpen,deleteTarget,tourStep,subjects,topics]);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("studyflow_theme", theme); }, [theme]);
  useEffect(()=>{const colors:Record<string,string>={lime:"#c8f05a",violet:"#a78bfa",pink:"#f472b6",blue:"#60a5fa",graphite:"#94a3b8"};const color=colors[accent]??accent;document.documentElement.dataset.accent=colors[accent]?accent:"custom";document.documentElement.style.setProperty("--accent",color);document.documentElement.style.setProperty("--lime",color);document.documentElement.style.setProperty("--accent-soft",`color-mix(in srgb, ${color} 16%, white)`);document.documentElement.style.setProperty("--accent-ink",`color-mix(in srgb, ${color} 68%, #182018)`);document.documentElement.style.setProperty("--accent-glow",`color-mix(in srgb, ${color} 35%, transparent)`);localStorage.setItem("studyflow_accent",accent)},[accent]);
  useEffect(() => {
    let frame = 0;
    const move = (event: PointerEvent) => {
      if (frame) cancelAnimationFrame(frame);
      frame = requestAnimationFrame(() => {
        document.documentElement.style.setProperty("--cursor-x", `${event.clientX}px`);
        document.documentElement.style.setProperty("--cursor-y", `${event.clientY}px`);
      });
    };
    window.addEventListener("pointermove", move, { passive: true });
    return () => { window.removeEventListener("pointermove", move); if (frame) cancelAnimationFrame(frame); };
  }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(null), 3200); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => { if (!welcome || !user) return; const timer=window.setTimeout(()=>setWelcome(false),1800); return()=>window.clearTimeout(timer); },[welcome,user]);
  useEffect(() => { const back=(event:PopStateEvent)=>{const next=event.state?.studyflowView as View|undefined;if(next)setView(next)};window.addEventListener("popstate",back);return()=>window.removeEventListener("popstate",back)},[]);
  useEffect(() => { if(!authenticated)return;const current=history.state?.studyflowView;if(!current)history.replaceState({studyflowView:view},"",`#${view}`);else if(current!==view)history.pushState({studyflowView:view},"",`#${view}`)},[authenticated,view]);
  useEffect(()=>{if(view!=="subjects"||!subjects.length)return;const frame=requestAnimationFrame(()=>{document.querySelectorAll<HTMLElement>(".subject-grid .subject-card").forEach((card,index)=>{const subject=subjects[index];if(!subject)return;card.tabIndex=0;card.setAttribute("role","button");card.setAttribute("aria-label",`Otwórz tematy przedmiotu ${subject.name}`);card.onclick=event=>{if((event.target as HTMLElement).closest("button"))return;setTopicScope(subject.subject_uid);setFocusedTopic(null);setView("topics")};card.onkeydown=event=>{if((event.key==="Enter"||event.key===" ")&&!(event.target as HTMLElement).closest("button")){event.preventDefault();setTopicScope(subject.subject_uid);setFocusedTopic(null);setView("topics")}}})});return()=>{cancelAnimationFrame(frame);document.querySelectorAll<HTMLElement>(".subject-grid .subject-card").forEach(card=>{card.onclick=null;card.onkeydown=null})}},[view,subjects]);
  useEffect(() => { const out = () => setAuthenticated(false); addEventListener("studyflow:logout", out); return () => removeEventListener("studyflow:logout", out); }, []);
  const done = tasks.filter(t => t.is_done).length;
  const todayKey=localDay(new Date());
  const todayMinutes=sessions.filter(session=>localDay(new Date(session.started_at))===todayKey).reduce((sum,session)=>sum+(session.duration_minutes??0),0);
  const weekStart=new Date();weekStart.setDate(weekStart.getDate()-6);
  const weekMinutes=sessions.filter(session=>localDay(new Date(session.started_at))>=localDay(weekStart)).reduce((sum,session)=>sum+(session.duration_minutes??0),0);
  const filtered = useMemo(() => {const today=localDay(new Date());const week=new Date();week.setDate(week.getDate()+7);return tasks.filter(t => t.title.toLowerCase().includes(search.toLowerCase()) && (!taskSubject || topics.find(x=>x.topic_uid===t.topic_uid)?.subject_uid===taskSubject) && (!taskTopic || t.topic_uid===taskTopic) && (!taskPriority || t.priority===taskPriority) && (taskStatus==="all" || (taskStatus==="done" ? t.is_done : !t.is_done))&&(taskWhen==="all"||!!t.deadline&&(taskWhen==="today"?localDay(new Date(t.deadline))===today:taskWhen==="week"?localDay(new Date(t.deadline))>=today&&localDay(new Date(t.deadline))<=localDay(week):localDay(new Date(t.deadline))<today)))}, [tasks, topics, search, taskSubject, taskTopic, taskPriority, taskStatus,taskWhen]);
  const filteredTopics=useMemo(()=>topics.filter(topic=>(!topicScope||topic.subject_uid===topicScope)&&(!topicDifficulty||topic.difficulty===topicDifficulty)&&(topicStatus==="all"||(topicStatus==="done"?topic.is_done:!topic.is_done))),[topics,topicScope,topicDifficulty,topicStatus]);
  const topicName = (id: string) => { const topic=topics.find(t=>t.topic_uid===id); const subject=subjects.find(s=>s.subject_uid===topic?.subject_uid); return topic ? `${subject?.name ?? "Przedmiot"} · ${topic.name}` : "Bez tematu"; };
  async function toggle(task: Task) { try { const updated={...task,is_done:!task.is_done};await api.updateTask(task.task_uid, { is_done: updated.is_done }); setTasks(v => v.map(t => t.task_uid === task.task_uid ? updated : t));setDetailTask(current=>current?.task_uid===task.task_uid?updated:current);setToast({message:updated.is_done?"Zadanie oznaczono jako wykonane — dobra robota!":"Zadanie oznaczono jako niewykonane",type:"success"}); } catch(err) { setToast({message:err instanceof Error?err.message:"Nie udało się zmienić zadania",type:"error"}); } }
  function remove(id: string) { const task = tasks.find(item => item.task_uid === id); if (task) setDeleteTarget({kind:"task",id,name:task.title}); }
  function removeSubject(subject: Subject) { setSubjectMenu(null); setDeleteTarget({kind:"subject",id:subject.subject_uid,name:subject.name}); }
  function removeTopic(topic: Topic) { setDeleteTarget({kind:"topic",id:topic.topic_uid,name:topic.name}); }
  function removeSession(session: Session) { setDeleteTarget({kind:"session",id:session.study_uid,name:session.title||`Sesja ${fmtDate(session.started_at)}`}); }
  async function toggleTopic(topic: Topic) { try { const updated={...topic,is_done:!topic.is_done};await api.updateTopic(topic.topic_uid,{is_done:updated.is_done});setTopics(value=>value.map(item=>item.topic_uid===topic.topic_uid?updated:item));setDetailTopic(current=>current?.topic_uid===topic.topic_uid?updated:current);setToast({message:updated.is_done?"Temat oznaczony jako ukończony":"Temat ponownie aktywny",type:"success"}); } catch(err) { setToast({message:err instanceof Error?err.message:"Nie udało się zmienić tematu",type:"error"}); } }
  function openTopicDetail(topic:Topic){setDetailTopic(topic);setView("topic-detail")}
  function openTaskDetail(task:Task){setDetailTask(task);setView("task-detail")}
  function openSessionDetail(session:Session){setDetailSession(session);setView("session-detail")}
  async function confirmDelete() { if (!deleteTarget) return; setDeleting(true); try { if(deleteTarget.kind==="subject") await api.deleteSubject(deleteTarget.id); else if(deleteTarget.kind==="topic") await api.deleteTopic(deleteTarget.id); else if(deleteTarget.kind==="session") await api.deleteSession(deleteTarget.id); else await api.deleteTask(deleteTarget.id); if(deleteTarget.kind==="session"){setDetailSession(null);setView("sessions")} setToast({message:`Usunięto: ${deleteTarget.name}`,type:"success"}); setDeleteTarget(null); await load(); } catch(err) { setToast({message:err instanceof Error?err.message:"Nie udało się usunąć",type:"error"}); } finally { setDeleting(false); } }
  function startTask() { setTaskDraftDeadline(undefined);if (!subjects.length) { setView("subjects"); setModal("subject"); return; } if (!topics.length) { setView("topics"); setModal("topic"); return; } setModal("task"); }
  function startTaskOnDate(date:string){if(!subjects.length){setView("subjects");setModal("subject");return}if(!topics.length){setView("topics");setModal("topic");return}setTaskDraftDeadline(`${date}T12:00`);setModal("task")}
  function startSessionForTask(task:Task){setSessionDraftTask(task);setModal("session")}
  async function duplicateTask(task:Task){try{await api.addTask({title:`${task.title} — kopia`,topic_uid:task.topic_uid,deadline:task.deadline,priority:task.priority,notes:task.notes});await load();setToast({message:"Zadanie zostało skopiowane",type:"success"})}catch(err){setToast({message:err instanceof Error?err.message:"Nie udało się skopiować zadania",type:"error"})}}
  async function bulkComplete(){try{await Promise.all([...selectedTaskIds].map(id=>api.updateTask(id,{is_done:true})));setSelectedTaskIds(new Set());setBulkMode(false);await load();setToast({message:"Zaznaczone zadania ukończone",type:"success"})}catch(err){setToast({message:err instanceof Error?err.message:"Nie udało się zaktualizować zadań",type:"error"})}}
  async function moveTaskToDate(task:Task,date:string){const previous=new Date(task.deadline??`${date}T12:00:00`);const hours=Number.isNaN(previous.getTime())?18:previous.getHours();const minutes=Number.isNaN(previous.getTime())?0:previous.getMinutes();const value=new Date(`${date}T${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:00`).toISOString();await api.updateTask(task.task_uid,{deadline:value});await load()}
  function logout() { clearToken(); setAuthenticated(false); }
  if (!authenticated) return <><Auth onReady={(newAccount) => {setProfileOpen(false);setWelcome(!newAccount);setAuthenticated(true)}} /><button className="auth-theme" onClick={() => setTheme(theme === "light" ? "dark" : "light")} aria-label="Zmień motyw">{theme === "light" ? <Moon /> : <Sun />}</button></>;
  return <div className="app-shell">
    <div className="ambient-mark ambient-one" aria-hidden="true"><i/><i/><i/></div><div className="ambient-mark ambient-two" aria-hidden="true"><i/><i/></div>
    <aside className={menu ? "sidebar open" : "sidebar"}><div className="side-head"><Brand onHome={()=>{setView("overview");setMenu(false)}} /><button className="icon mobile-close" onClick={() => setMenu(false)}><X /></button></div><nav>
      <button className={view === "overview" ? "active" : ""} onClick={() => { setView("overview"); setMenu(false); }}><LayoutDashboard />Przegląd</button>
      <button className={view === "subjects" ? "active" : ""} onClick={() => { setView("subjects"); setMenu(false); }}><BookOpen />Przedmioty</button>
      <button className={view === "topics" ? "active" : ""} onClick={() => { setTopicScope(null); setFocusedTopic(null); setView("topics"); setMenu(false); }}><Layers3 />Tematy{topics.some(t=>!t.is_done)&&<span>{topics.filter(t=>!t.is_done).length}</span>}</button>
      <button className={view === "tasks" ? "active" : ""} onClick={() => { setView("tasks"); setMenu(false); }}><ListTodo />Zadania{tasks.some(t=>!t.is_done)&&<span>{tasks.filter(t => !t.is_done).length}</span>}</button>
      <button className={view === "sessions" ? "active" : ""} onClick={() => { setView("sessions"); setMenu(false); }}><History />Sesje nauki</button>
      <button className={view === "calendar" ? "active" : ""} onClick={() => { setView("calendar"); setMenu(false); }}><CalendarDays />Kalendarz</button>
    </nav><div className="side-focus"><span><Sparkles size={14} /> Dobra passa</span><strong>{studyStreak(sessions)} dni</strong><p>Wiele sesji jednego dnia liczy się jako jeden dzień.</p></div><button className="theme-toggle" onClick={() => setTheme(theme === "light" ? "dark" : "light")}>{theme === "light" ? <Moon /> : <Sun />}<span>{theme === "light" ? "Ciemny motyw" : "Jasny motyw"}</span></button><div className="sidebar-accent"><AccentPicker value={accent} change={setAccent}/></div><div className={settingsOpen?"profile-settings open":"profile-settings"}><button className="profile" onClick={()=>setSettingsOpen(open=>!open)} aria-expanded={settingsOpen}><span>{avatar?<img src={avatar} alt="Zdjęcie profilowe"/>:initials(user?.username ?? "SF")}</span><div><strong>{user?.username}</strong><small>Twoje konto</small></div><Settings size={18}/></button>{settingsOpen&&<div className="profile-settings-menu"><button onClick={()=>{setSettingsOpen(false);setProfileOpen(true)}}><ShieldCheck/>Ustawienia konta</button><button onClick={()=>{setSettingsOpen(false);setPreferencesOpen(true)}}><Settings/>Ustawienia użytkownika</button><button onClick={()=>{setSettingsOpen(false);setMenu(false);setTourStep(1)}}><HelpCircle/>Uruchom samouczek</button><button onClick={logout}><LogOut/>Wyloguj się</button></div>}</div></aside>
    {menu && <div className="menu-shade" onClick={() => setMenu(false)} />}
    <main className="content"><header><button className="icon menu-button" onClick={() => setMenu(true)}><Menu /></button>{view!=="overview"&&<button className="back-button" onClick={()=>history.back()}><ArrowLeft/>Wróć</button>}<div><span className="kicker">{new Intl.DateTimeFormat("pl-PL", { weekday: "long", day: "numeric", month: "long" }).format(new Date())}</span><h1>{view === "overview" ? `Cześć, ${user?.username ?? "Uczniu"} 👋` : view === "subjects" ? "Twoje przedmioty" : view === "topics" ? "Twoje tematy" : view === "calendar" ? "Kalendarz terminów" : view === "sessions" ? "Historia nauki" : view === "topic-detail" ? "Szczegóły tematu" : view === "task-detail" ? "Szczegóły zadania" : view === "session-detail" ? "Szczegóły sesji" : "Twoje zadania"}</h1></div>{!['calendar','topic-detail','task-detail','session-detail'].includes(view)&&<button className="primary" onClick={() => view === "subjects" ? setModal("subject") : view === "topics" ? (subjects.length ? setModal("topic") : setModal("subject")) : view === "sessions" ? setModal("session") : startTask()}><CirclePlus size={18} />{view === "subjects" ? "Dodaj przedmiot" : view === "topics" ? "Dodaj temat" : view === "sessions" ? "Zapisz sesję" : "Dodaj zadanie"}</button>}</header>
      {loading ? <div className="loading-page"><span className="loader" /><p>Układamy Twój dzień…</p></div> : <>
      {view === "overview" && <div className="dashboard-view view-enter">
        <section className="dashboard-ai"><span><Sparkles/></span><div><small>STUDYFLOW AI</small><h2>Twój asystent nauki</h2><p>Porozmawiaj z T3ACH albo szybko przygotuj notatkę lub plan nauki.</p></div><div><button className="primary" onClick={()=>setAiNotesOpen(true)}><Sparkles/>Otwórz Asystenta AI</button><button className="secondary" onClick={()=>setAiHistoryOpen(true)}><History/>Historia materiałów</button></div></section>
        {user&&<StudyHub user={user} subjects={subjects} topics={topics} tasks={tasks} plans={plans} reviews={reviews} onChanged={load} openTask={openTaskDetail} openMaterials={()=>setAiHistoryOpen(true)}/>}
        <section className="hero"><div><span className="eyebrow"><span /> DZISIAJ</span><h2>Zrób jedną rzecz.<br /><em>Potem kolejną.</em></h2><p>Masz {tasks.filter(t => !t.is_done).length} otwartych zadań. Wybierz jedno i ruszaj — reszta może chwilę poczekać.</p><button className="light-button" onClick={() => setView("tasks")}><Play size={16} fill="currentColor" /> Zacznij działać</button></div><div className="hero-ring"><svg viewBox="0 0 120 120"><circle cx="60" cy="60" r="51" /><circle className="progress" cx="60" cy="60" r="51" style={{ strokeDashoffset: 320 - 320 * (tasks.length ? done/tasks.length : 0) }} /></svg><strong>{tasks.length ? Math.round(done/tasks.length*100) : 0}%</strong><span>ukończone</span></div></section>
        <section className="stats"><article><span className="stat-icon mint"><Check /></span><div><small>Ukończone zadania</small><strong>{done}<i> / {tasks.length}</i></strong></div></article><article><span className="stat-icon violet"><Clock3 /></span><div><small>Nauka dzisiaj</small><strong>{Math.floor(todayMinutes/60)}h {todayMinutes%60}min</strong><small>Ostatnie 7 dni: {Math.floor(weekMinutes/60)}h {weekMinutes%60}min</small></div></article><article><span className="stat-icon orange"><BookOpen /></span><div><small>Aktywne przedmioty</small><strong>{subjects.length}</strong></div></article></section>
        <div className="dashboard-grid"><section className="panel float-panel"><div className="panel-head"><div><span className="kicker">NAJBLIŻSZE</span><h3>Zadania na teraz</h3></div><button className="text-button" onClick={() => setView("tasks")}>Wszystkie <ChevronRight /></button></div>{!topics.length ? <Empty text="Dodaj temat, aby utworzyć pierwsze zadanie" action={() => setView(subjects.length ? "topics" : "subjects")} /> : <TaskList tasks={tasks.filter(t => !t.is_done).slice(0,5)} topicName={topicName} toggle={toggle} remove={remove} open={openTaskDetail} edit={task=>setEditing({kind:"task",value:task})} />}</section>
        <section className="panel subjects-mini"><div className="panel-head"><div><span className="kicker">PRZEDMIOTY</span><h3>Twój kierunek</h3></div><button className="icon" onClick={() => setModal("subject")}><CirclePlus /></button></div>{subjects.slice(0,4).map((s,i) => <button className="subject-link" key={s.subject_uid} style={{"--subject-color":s.color} as React.CSSProperties} onClick={()=>{setTopicScope(s.subject_uid);setView("topics")}}><span className="subject-letter" style={{background:s.color}}>{s.name[0]}</span><div><strong>{s.name}</strong><small>{topics.filter(t => t.subject_uid === s.subject_uid).length} tematów</small></div><span className="date"><CalendarDays />{fmtDate(s.exam_date)}</span><ChevronRight/></button>)}{!subjects.length && <Empty text="Dodaj pierwszy przedmiot" action={() => setModal("subject")} />}</section><DashboardCalendar tasks={tasks} subjects={subjects} open={()=>setView("calendar")} openTask={openTaskDetail} addTask={startTaskOnDate}/></div>
        {user&&<PlanBoard plans={plans} user={user} onChanged={load}/>}
      </div>}
      {view === "subjects" && <SubjectsView subjects={subjects} archived={archivedSubjects} topics={topics} add={()=>setModal("subject")} edit={subject=>setEditing({kind:"subject",value:subject})} remove={removeSubject} openTopics={(subject,topic)=>{setTopicScope(subject.subject_uid);setFocusedTopic(topic?.topic_uid??null);setView("topics")}} onChanged={load}/>}
      {view === "topics" && <section className="subject-view view-enter">{!subjects.length ? <Onboarding title="Najpierw dodaj przedmiot" text="Każdy temat musi należeć do przedmiotu. Utwórz pierwszy przedmiot, a zaraz potem dodasz do niego materiał." action="Dodaj przedmiot" click={() => setModal("subject")} /> : !topics.length ? <Onboarding title="Podziel materiał na tematy" text="Tematy zamieniają duży przedmiot w konkretne etapy. Dodaj pierwszy, a następnie przypisz do niego zadania." action="Dodaj pierwszy temat" click={() => setModal("topic")} /> : <><div className="topic-filter-bar"><label>Przedmiot<SelectField name="topic-subject-filter" defaultValue={topicScope??""} options={[{value:"",label:"Wszystkie przedmioty"},...subjects.map(s=>({value:s.subject_uid,label:s.name}))]} onChange={v=>{setTopicScope(v||null);setFocusedTopic(null)}}/></label><label>Status<SelectField name="topic-status-filter" defaultValue={topicStatus} options={[{value:"open",label:"Do zrobienia"},{value:"done",label:"Ukończone"},{value:"all",label:"Wszystkie"}]} onChange={setTopicStatus}/></label><label>Trudność<SelectField name="topic-difficulty-filter" defaultValue={topicDifficulty} options={[{value:"",label:"Każdy poziom"},{value:"Łatwy",label:"Łatwy"},{value:"Średni",label:"Średni"},{value:"Trudny",label:"Trudny"}]} onChange={setTopicDifficulty}/></label><strong>{filteredTopics.length} wyników</strong></div>{filteredTopics.length?<div className="topic-grid">{filteredTopics.map(topic => <article className={`${topic.is_done ? "topic-card complete" : "topic-card"}${focusedTopic===topic.topic_uid ? " focused" : ""}`} key={topic.topic_uid} style={{"--subject-color":subjects.find(subject=>subject.subject_uid===topic.subject_uid)?.color||"var(--accent)"} as React.CSSProperties}><button className="topic-check" onClick={()=>toggleTopic(topic)}>{topic.is_done && <Check />}</button><button className="topic-main" onClick={()=>openTopicDetail(topic)}><span className="kicker">{subjects.find(s=>s.subject_uid===topic.subject_uid)?.name}</span><h3>{topic.name}</h3><p>{topic.difficulty || "Bez poziomu"} · {tasks.filter(t=>t.topic_uid===topic.topic_uid).length} zadań · kliknij, aby zobaczyć</p></button><div className="row-actions"><button className="icon" title="Edytuj temat" onClick={()=>setEditing({kind:"topic",value:topic})}><Pencil /></button><button className="icon topic-delete" title="Usuń temat" onClick={()=>removeTopic(topic)}><Trash2 /></button></div></article>)}</div>:<Empty text="Brak tematów pasujących do wybranych filtrów"/>}</>}</section>}
      {view === "tasks" && <section className="panel task-view view-enter">{!subjects.length || !topics.length ? <Onboarding title={!subjects.length ? "Najpierw utwórz przedmiot" : "Zadanie potrzebuje tematu"} text={!subjects.length ? "Przedmiot i temat pomagają zachować porządek. Zaczniemy od pierwszego kroku." : "Dodaj temat do jednego z przedmiotów, a potem od razu utworzysz swoje pierwsze zadanie."} action={!subjects.length ? "Dodaj przedmiot" : "Dodaj temat"} click={() => setModal(!subjects.length ? "subject" : "topic")} /> : <>
        <div className="tasks-toolbar"><div className="search"><Search /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Szukaj po nazwie…" /></div><span>{filtered.length} wyników</span><button className="secondary compact" onClick={()=>{setBulkMode(value=>!value);setSelectedTaskIds(new Set())}}>{bulkMode?"Zakończ zaznaczanie":"Zaznacz wiele"}</button>{bulkMode&&<button className="primary compact" disabled={!selectedTaskIds.size} onClick={()=>void bulkComplete()}>Ukończ wybrane ({selectedTaskIds.size})</button>}</div>
        <div className="filter-grid"><label>Przedmiot<SelectField name="filter-subject" defaultValue={taskSubject} options={[{value:"",label:"Wszystkie przedmioty"},...subjects.map(s=>({value:s.subject_uid,label:s.name}))]} onChange={v=>{setTaskSubject(v);setTaskTopic("");}}/></label><label>Temat<SelectField name={`filter-topic-${taskSubject}`} defaultValue={taskTopic} options={[{value:"",label:"Wszystkie tematy"},...topics.filter(t=>!taskSubject||t.subject_uid===taskSubject).map(t=>({value:t.topic_uid,label:t.name}))]} onChange={setTaskTopic}/></label><label>Status<SelectField name="filter-status" defaultValue={taskStatus} options={[{value:"open",label:"Do zrobienia"},{value:"done",label:"Ukończone"},{value:"all",label:"Wszystkie"}]} onChange={setTaskStatus}/></label><label>Priorytet<SelectField name="filter-priority" defaultValue={taskPriority} options={[{value:"",label:"Każdy priorytet"},{value:"HIGH",label:"Wysoki"},{value:"MEDIUM",label:"Średni"},{value:"LOW",label:"Niski"}]} onChange={setTaskPriority}/></label><label>Termin<SelectField name="filter-when" defaultValue={taskWhen} options={[{value:"all",label:"Każdy termin"},{value:"today",label:"Dzisiaj"},{value:"week",label:"Najbliższy tydzień"},{value:"overdue",label:"Zaległe"}]} onChange={setTaskWhen}/></label></div>
        <TaskList tasks={filtered} topicName={topicName} toggle={toggle} remove={remove} open={openTaskDetail} edit={task=>setEditing({kind:"task",value:task})} duplicate={task=>void duplicateTask(task)} selected={selectedTaskIds} onSelect={bulkMode?id=>setSelectedTaskIds(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next}):undefined}/></>}</section>}
      {view === "calendar" && <><StudyCalendarView tasks={tasks} subjects={subjects} topics={topics} plans={plans} timeZone={user?.timezone??Intl.DateTimeFormat().resolvedOptions().timeZone} openTask={openTaskDetail} addTaskOnDate={startTaskOnDate} moveTask={moveTaskToDate} openPlan={()=>setView("overview")}/>{user&&<PlanBoard plans={plans} user={user} onChanged={load}/>}</>}
      {view === "sessions" && <SessionHistory sessions={sessions} subjects={subjects} topics={topics} tasks={tasks} remove={removeSession} open={openSessionDetail} edit={setSessionEditing} add={()=>setModal("session")}/>}
      {view === "topic-detail" && detailTopic && (
        <TopicDetail
          topic={detailTopic}
          subject={subjects.find(subject=>subject.subject_uid===detailTopic.subject_uid)}
          tasks={tasks.filter(task=>task.topic_uid===detailTopic.topic_uid)}
          topicName={topicName}
          toggleTask={toggle}
          removeTask={remove}
          openTask={openTaskDetail}
          editTask={task=>setEditing({kind:"task",value:task})}
          editTopic={()=>setEditing({kind:"topic",value:detailTopic})}
          toggleTopic={()=>toggleTopic(detailTopic)}
          addTask={startTask}
        />
      )}
      {view === "task-detail" && detailTask && (
        <div className="task-detail-view">
        <TaskDetail
          task={detailTask}
          topics={topics}
          subjects={subjects}
          sessions={sessions.filter(session=>session.task_uid===detailTask.task_uid)}
          edit={() => setEditing({ kind: "task", value: detailTask })}
          toggle={() => toggle(detailTask)}
          openSession={openSessionDetail}
          addSession={()=>startSessionForTask(detailTask)}
        />
        <TaskSessionsOverview sessions={sessions.filter(session=>session.task_uid===detailTask.task_uid)} openSession={openSessionDetail} addSession={()=>startSessionForTask(detailTask)}/>
        <TaskAiMaterials taskId={detailTask.task_uid}/>
        <TaskSessionNotes sessions={sessions.filter(session=>session.task_uid===detailTask.task_uid)} openSession={openSessionDetail}/>
        <section className="task-danger-zone">
          <div><span className="kicker">STREFA ZARZĄDZANIA</span><h3>Usuń zadanie</h3><p>Zadanie oraz jego powiązania zostaną trwale usunięte.</p></div>
          <button className="delete-button" onClick={()=>remove(detailTask.task_uid)}><Trash2/>Usuń zadanie</button>
        </section>
        </div>
      )}
      {view === "session-detail" && detailSession && (
        <div className="session-detail-view">
        <SessionDetailV2
          session={detailSession}
          subjects={subjects}
          topics={topics}
          tasks={tasks}
          edit={() => setSessionEditing(detailSession)}
        />
        <section className="task-danger-zone"><div><span className="kicker">STREFA ZARZĄDZANIA</span><h3>Usuń sesję</h3><p>Ta sesja nauki zostanie trwale usunięta.</p></div><button className="delete-button" onClick={()=>removeSession(detailSession)}><Trash2/>Usuń sesję</button></section>
        </div>
      )}
      </>}
    </main>
    {modal && user && <ModalForm type={modal} subjects={subjects} topics={topics} tasks={tasks} userId={user.user_uid} initialDeadline={taskDraftDeadline} initialTask={sessionDraftTask} close={() => {setModal(null);setSessionDraftTask(null)}} done={() => { setModal(null);setSessionDraftTask(null);setTaskDraftDeadline(undefined);setToast({message:"Zapisano pomyślnie",type:"success"}); load(); }} />}
    {editing && <EditForm target={editing} subjects={subjects} topics={topics} close={() => setEditing(null)} done={() => { setEditing(null); setToast({message:"Zmiany zostały zapisane",type:"success"}); load(); }} />}
    {profileOpen&&user&&<ProfileForm user={user} avatar={avatar} changeAvatar={value=>{setAvatar(value);const key=`studyflow_avatar_${user.user_uid}`;if(value)localStorage.setItem(key,value);else localStorage.removeItem(key)}} close={()=>setProfileOpen(false)} done={()=>{setProfileOpen(false);setToast({message:"Profil został zaktualizowany",type:"success"});load();}} logout={logout}/>}
    {preferencesOpen&&user&&<PreferencesForm user={user} close={()=>setPreferencesOpen(false)} done={()=>{setPreferencesOpen(false);setToast({message:"Ustawienia zostały zapisane",type:"success"});void load()}}/>}
    {sessionEditing&&<SessionEditForm session={sessionEditing} subjects={subjects} topics={topics} tasks={tasks} close={()=>setSessionEditing(null)} done={()=>{setSessionEditing(null);setToast({message:"Sesja została zaktualizowana",type:"success"});load()}}/>}
    {deleteTarget && <div className="modal-backdrop" onMouseDown={()=>!deleting&&setDeleteTarget(null)}><div className="confirm-dialog" onMouseDown={e=>e.stopPropagation()}><span className="danger-mark"><Trash2 /></span><h2>Na pewno usunąć?</h2><p><strong>„{deleteTarget.name}”</strong>{deleteTarget.kind === "subject" ? " oraz wszystkie jego tematy i zadania zostaną usunięte." : deleteTarget.kind === "topic" ? " oraz powiązane zadania zostaną usunięte." : " zostanie trwale usunięte."}</p><div><button className="secondary" disabled={deleting} onClick={()=>setDeleteTarget(null)}>Anuluj</button><button className="delete-button" disabled={deleting} onClick={confirmDelete}>{deleting?<span className="loader"/>:<><Trash2 />Usuń</>}</button></div></div></div>}
    {toast && <div className={`toast ${toast.type}`} role="status"><span>{toast.type === "success" ? <Check /> : <X />}</span><p>{toast.message}</p><button onClick={()=>setToast(null)}><X /></button></div>}
    {tourStep>0&&<GuidedTourV2 step={tourStep} navigate={setView} next={()=>{if(tourStep===GUIDED_TOUR_STEPS){localStorage.setItem(`studyflow_tour_done_${user?.user_uid}`,"1");setTourStep(0)}else setTourStep(tourStep+1)}} previous={()=>setTourStep(step=>Math.max(1,step-1))} close={()=>{localStorage.setItem(`studyflow_tour_done_${user?.user_uid}`,"1");setTourStep(0)}}/>}
    {welcome&&user&&<div className="welcome-screen"><div><span><Sparkles/></span><small>WITAJ W STUDYFLOW</small><h2>Cześć, {user.username}!</h2><p>Twój plan jest gotowy.</p></div></div>}
    <div className="floating-actions"><button className="floating-ai" onClick={()=>setT3achOpen(true)} title="Porozmawiaj z T3ACH"><Sparkles/><span>Asystent AI</span></button><button className="floating-session" onClick={() => setModal("session")} title="Zapisz sesję nauki"><Clock3 /><span>Zapisz naukę</span></button></div>
    {t3achOpen&&<VoiceT3ach close={()=>setT3achOpen(false)} onSaved={load} openGenerator={()=>{setT3achOpen(false);setAiNotesOpen(true)}} memory={t3achMemory} remember={setT3achMemory}/>}
    {aiNotesOpen&&<AiAssistantV2 subjects={subjects} topics={topics} tasks={tasks} initialTopic={view==="topic-detail"?detailTopic:null} onSaved={load} onNeedSubject={()=>{setAiNotesOpen(false);setModal("subject")}} openT3ach={()=>{setAiNotesOpen(false);setT3achOpen(true)}} close={()=>setAiNotesOpen(false)}/>}
    {aiHistoryOpen&&<AiHistoryModalV2 topics={topics} close={()=>setAiHistoryOpen(false)}/>}
    {user&&!user.onboarding_complete&&!loading&&tourStep===0&&localStorage.getItem(`studyflow_tour_done_${user.user_uid}`)==="1"&&<FirstRunWizard user={user} onDone={load}/>}
  </div>;
}

function Empty({ text, action }: { text: string; action?: () => void }) { return <div className="empty"><Sparkles /><p>{text}</p>{action && <button onClick={action}>Dodaj teraz</button>}</div>; }
function GuidedTourV2({step,navigate,next,previous,close}:{step:number;navigate:(view:View)=>void;next:()=>void;previous:()=>void;close:()=>void}) {
  const steps:{title:string;text:string;selector:string|null;view:View;position:string}[]=[
    {title:"Witaj w StudyFlow",text:"Najpierw pokażemy Ci aplikację. Potem ustawisz własny skrót i przygotujesz pierwszy przedmiot.",selector:null,view:"overview",position:"center"},
    {title:"Twój dashboard",text:"Tutaj widzisz postęp, najbliższe zadania, przedmioty, kalendarz i aktualną passę nauki.",selector:".dashboard-view",view:"overview",position:"right"},
    {title:"Przedmioty",text:"Od przedmiotu zaczyna się organizacja. Dodasz tu egzamin, a materiał podzielisz później na mniejsze części.",selector:".subject-view .subject-grid, .subject-view .onboarding",view:"subjects",position:"right"},
    {title:"Tematy",text:"Tematy porządkują zakres przedmiotu. Możesz je filtrować, oznaczać jako ukończone i otwierać ich szczegóły.",selector:".subject-view .topic-grid, .subject-view .onboarding",view:"topics",position:"right"},
    {title:"Zadania",text:"Tutaj zapisujesz konkretne rzeczy do zrobienia, terminy i priorytety. Filtry pomagają szybko znaleźć właściwe zadanie.",selector:".task-view",view:"tasks",position:"right"},
    {title:"Sesje nauki",text:"Zapisuj czas i efekty pracy. Kilka słów wystarczy, aby AI przygotowało tytuł oraz czytelną notatkę z sesji.",selector:".session-view",view:"sessions",position:"right"},
    {title:"Kalendarz",text:"Zadania i egzaminy trafiają do wspólnego kalendarza. Kliknięcie dnia pokazuje jego dokładny plan.",selector:".calendar-view",view:"calendar",position:"right"},
    {title:"Szybki zapis nauki",text:"Po zakończeniu pracy użyj tego przycisku, aby zapisać czas, zakres i notatkę. AI może przygotować tytuł oraz podsumowanie z kilku słów.",selector:".floating-session",view:"overview",position:"left"},
    {title:"Asystent AI",text:"Asystent tworzy notatki i plany nauki, zapisuje je przy zadaniu oraz potrafi założyć nowy temat i zadanie.",selector:".floating-ai",view:"overview",position:"left"},
    {title:"Jasny i ciemny wygląd",text:"Ten przycisk błyskawicznie przełącza jasny oraz ciemny wariant interfejsu. Wybrany tryb zapisuje się automatycznie.",selector:".theme-toggle",view:"overview",position:"right"},
    {title:"Konto i ustawienia",text:"W menu profilu osobno znajdziesz dane konta oraz ustawienia wyglądu, nauki i skrótu. Samouczek możesz uruchomić ponownie.",selector:".profile",view:"overview",position:"right"},
  ];
  const current=steps[step-1]??steps[0];
  const [spotlight,setSpotlight]=useState<React.CSSProperties|null>(null);
  useEffect(()=>{navigate(current.view);setSpotlight(null);let target:Element|null=null;const followTimers:number[]=[];const place=()=>{if(!target)return;const rect=target.getBoundingClientRect();const rawRadius=parseFloat(getComputedStyle(target).borderRadius)||16;const gap=8;setSpotlight({left:Math.max(8,rect.left-gap),top:Math.max(8,rect.top-gap),width:Math.min(window.innerWidth-16,rect.width+gap*2),height:Math.min(window.innerHeight-16,rect.height+gap*2),borderRadius:rawRadius+gap})};const timer=window.setTimeout(()=>{target=current.selector?document.querySelector(current.selector):null;target?.classList.add("tour-highlight");target?.scrollIntoView({behavior:"smooth",block:"center"});[0,120,280,520].forEach(delay=>followTimers.push(window.setTimeout(place,delay)))},180);window.addEventListener("resize",place);return()=>{window.clearTimeout(timer);followTimers.forEach(id=>window.clearTimeout(id));window.removeEventListener("resize",place);target?.classList.remove("tour-highlight")}},[step]);
  return <div className={`tour-backdrop tour-v2 ${current.position}`}>{spotlight&&<div className="tour-spotlight" style={spotlight}/>}<div className="tour-card"><button className="icon tour-close" onClick={close}><X/></button><div className="tour-copy" key={step}><span className="tour-art"><Sparkles/></span><small>KROK {step} Z {steps.length}</small><h2>{current.title}</h2><p>{current.text}</p></div><div className="tour-progress"><i style={{width:`${step/steps.length*100}%`}}/></div><div className="tour-actions">{step>1&&<button className="secondary" onClick={previous}><ArrowLeft/>Wstecz</button>}<button className="primary" onClick={next}>{step===steps.length?"Zaczynamy":"Dalej"}<ArrowRight/></button></div><button className="skip-tour" onClick={close}>Pomiń samouczek</button></div></div>
}
function TopicDetail({topic,subject,tasks,topicName,toggleTask,removeTask,openTask,editTask,editTopic,toggleTopic,addTask}:{topic:Topic;subject?:Subject;tasks:Task[];topicName:(id:string)=>string;toggleTask:(task:Task)=>void;removeTask:(id:string)=>void;openTask:(task:Task)=>void;editTask:(task:Task)=>void;editTopic:()=>void;toggleTopic:()=>void;addTask:()=>void}) {const completed=tasks.filter(task=>task.is_done).length;const progress=tasks.length?Math.round(completed/tasks.length*100):0;const [displayProgress,setDisplayProgress]=useState(0);useEffect(()=>{const start=displayProgress;const difference=progress-start;const started=performance.now();let frame=0;const animate=(time:number)=>{const elapsed=Math.min((time-started)/550,1);const eased=1-Math.pow(1-elapsed,3);setDisplayProgress(Math.round(start+difference*eased));if(elapsed<1)frame=requestAnimationFrame(animate)};frame=requestAnimationFrame(animate);return()=>cancelAnimationFrame(frame)},[progress]);return <section className="detail-page topic-detail-page view-enter"><div className={topic.is_done?"detail-hero topic-detail-hero completed":"detail-hero topic-detail-hero"}><span className="topic-state">{topic.is_done?<><Check/>Temat ukończony</>:<><Layers3/>Temat w toku</>}</span><h2>{topic.name}</h2><p>{subject?.name??"Bez przedmiotu"} · {topic.difficulty||"Bez poziomu trudności"}</p><div><button className={topic.is_done?"completion-button completed":"completion-button"} onClick={toggleTopic}><span><Check/></span>{topic.is_done?"Oznacz jako aktywny":"Oznacz jako ukończony"}</button><button className="primary" onClick={editTopic}><Pencil/>Edytuj temat</button></div></div><div className="topic-detail-stats"><article><strong>{tasks.length}</strong><small>Wszystkie zadania</small></article><article><strong>{completed}</strong><small>Ukończone</small></article><article className="progress-stat"><strong>{displayProgress}%</strong><small>Postęp</small><div><i style={{width:`${displayProgress}%`}}/></div></article></div><section className="panel topic-task-panel"><div className="panel-head"><div><span className="kicker">ZADANIA TEMATU</span><h3>Plan pracy</h3></div><button className="primary compact" onClick={addTask}><CirclePlus/>Dodaj zadanie</button></div><TaskList tasks={tasks} topicName={topicName} toggle={toggleTask} remove={removeTask} open={openTask} edit={editTask}/></section></section>}
function TaskDetail({task,topics,subjects,sessions,edit,toggle,openSession,addSession}:{task:Task;topics:Topic[];subjects:Subject[];sessions:Session[];edit:()=>void;toggle:()=>void;openSession:(session:Session)=>void;addSession:()=>void}) {const topic=topics.find(t=>t.topic_uid===task.topic_uid);const subject=subjects.find(s=>s.subject_uid===topic?.subject_uid);return <section className="detail-page view-enter"><div className={task.is_done?"detail-hero task-detail-hero completed":"detail-hero task-detail-hero"}><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority==="HIGH"?"Wysoki priorytet":task.priority==="LOW"?"Niski priorytet":"Średni priorytet"}</span><h2>{task.title}</h2><p>{subject?.name} · {topic?.name}</p><div><button className={task.is_done?"completion-button completed":"completion-button"} onClick={toggle}><span><Check/></span>{task.is_done?"Przywróć zadanie":"Oznacz jako wykonane"}</button><button className="primary" onClick={edit}><Pencil/>Edytuj</button></div></div><div className="detail-grid"><article><CalendarDays/><small>Termin</small><strong>{task.deadline?new Intl.DateTimeFormat("pl-PL",{dateStyle:"long",timeStyle:"short"}).format(new Date(task.deadline)):"Bez terminu"}</strong></article><article><Layers3/><small>Temat</small><strong>{topic?.name??"Brak"}</strong></article></div><article className="detail-notes"><span className="kicker">NOTATKA</span><p>{task.notes||"Do tego zadania nie dodano jeszcze notatki."}</p></article><section className="panel related-sessions"><div className="panel-head"><div><span className="kicker">POWIĄZANA NAUKA</span><h3>Sesje tego zadania</h3></div><div className="related-session-actions"><strong>{sessions.length}</strong><button className="primary compact" onClick={addSession}><CirclePlus/>Dodaj sesję</button></div></div>{sessions.length?<div className="related-session-list">{sessions.map(session=><button key={session.study_uid} onClick={()=>openSession(session)}><span className="session-date"><b>{new Date(session.started_at).getDate()}</b><small>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(session.started_at))}</small></span><div><strong>{session.duration_minutes??0} min nauki</strong><p>{session.notes||"Bez notatki"}</p></div><ChevronRight/></button>)}</div>:<Empty text="Do tego zadania nie przypisano jeszcze sesji nauki."/>}</section></section>}
function SessionDetail({session,subjects,topics,tasks,edit}:{session:Session;subjects:Subject[];topics:Topic[];tasks:Task[];edit:()=>void}) {const subject=subjects.find(s=>s.subject_uid===session.subject_uid);const topic=topics.find(t=>t.topic_uid===session.topic_uid);const task=tasks.find(t=>t.task_uid===session.task_uid);return <section className="detail-page view-enter"><div className="detail-hero session-detail-hero"><span className="kicker">SESJA NAUKI</span><h2>{task?.title||topic?.name||subject?.name||"Sesja nauki"}</h2><p>{new Intl.DateTimeFormat("pl-PL",{dateStyle:"full",timeStyle:"short"}).format(new Date(session.started_at))}</p><div><button className="primary" onClick={edit}><Pencil/>Edytuj sesję</button></div></div><div className="detail-grid"><article><Clock3/><small>Czas nauki</small><strong>{session.duration_minutes??0} minut</strong></article><article><BookOpen/><small>Zakres</small><strong>{subject?.name}{topic&&` · ${topic.name}`}</strong></article></div><article className="detail-notes"><span className="kicker">NOTATKA Z SESJI</span><p>{session.notes||"Do tej sesji nie dodano notatki."}</p></article></section>}
function SessionHistory({sessions,subjects,topics,tasks,remove,open,edit,add}:{sessions:Session[];subjects:Subject[];topics:Topic[];tasks:Task[];remove:(s:Session)=>void;open:(s:Session)=>void;edit:(s:Session)=>void;add:()=>void}) { const total=sessions.reduce((n,s)=>n+(s.duration_minutes??0),0); return <section className="session-view view-enter"><div className="session-summary"><article><Clock3/><div><small>Łączny czas</small><strong>{Math.floor(total/60)}h {total%60}min</strong></div></article><article><History/><div><small>Liczba sesji</small><strong>{sessions.length}</strong></div></article><article><Sparkles/><div><small>Aktualna passa</small><strong>{studyStreak(sessions)} dni</strong></div></article></div>{!sessions.length?<Onboarding title="Zapisz pierwszą sesję" text="Po nauce zapisz czas, temat i krótką notatkę. Dzięki temu zobaczysz prawdziwy postęp, nie tylko wykonane zadania." action="Zapisz naukę" click={add}/>:<div className="session-list">{sessions.map(s=><article key={s.study_uid} onClick={()=>open(s)}><div className="session-date"><b>{new Date(s.started_at).getDate()}</b><span>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(s.started_at))}</span></div><div className="session-body"><span className="kicker">{subjects.find(x=>x.subject_uid===s.subject_uid)?.name}{s.topic_uid&&` · ${topics.find(x=>x.topic_uid===s.topic_uid)?.name}`}</span><h3>{s.task_uid?tasks.find(x=>x.task_uid===s.task_uid)?.title:"Sesja nauki"}</h3><p>{s.notes||"Brak notatki do tej sesji."}</p></div><strong className="session-time">{s.duration_minutes??0} min</strong><div className="row-actions"><button className="icon" onClick={e=>{e.stopPropagation();edit(s)}} title="Edytuj sesję"><Pencil/></button><button className="icon topic-delete" onClick={e=>{e.stopPropagation();remove(s)}} title="Usuń sesję"><Trash2/></button></div></article>)}</div>}</section> }
function DashboardCalendar({tasks,subjects,open,openTask,addTask}:{tasks:Task[];subjects:Subject[];open:()=>void;openTask:(task:Task)=>void;addTask:(date:string)=>void}) {
  const [expanded,setExpanded]=useState(false); const now=new Date();const [selectedDay,setSelectedDay]=useState(now.getDate());const first=new Date(now.getFullYear(),now.getMonth(),1);const offset=(first.getDay()+6)%7;const count=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();const cells=Array.from({length:offset+count},(_,i)=>i<offset?null:i-offset+1);const date=(d:number)=>`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;const upcoming=tasks.filter(task=>task.deadline&&!task.is_done&&new Date(task.deadline)>=new Date(now.getFullYear(),now.getMonth(),now.getDate())).sort((a,b)=>new Date(a.deadline!).getTime()-new Date(b.deadline!).getTime()).slice(0,3);const exams=subjects.filter(subject=>subject.exam_date&&subject.exam_date>=localDay(now)).sort((a,b)=>a.exam_date!.localeCompare(b.exam_date!)).slice(0,2);const selectedDate=date(selectedDay);const selectedTasks=tasks.filter(task=>!!task.deadline&&localDay(new Date(task.deadline))===selectedDate);const selectedExams=subjects.filter(subject=>subject.exam_date===selectedDate);
  return <section className={expanded?"dashboard-calendar expanded":"dashboard-calendar"}>
    <button type="button" className="mini-calendar-head" onClick={()=>setExpanded(value=>!value)} aria-expanded={expanded}>
      <div><span className="kicker">KALENDARZ</span><strong>{new Intl.DateTimeFormat("pl-PL",{month:"long",year:"numeric"}).format(now)}</strong></div>
      <span>{expanded?"Zwiń":"Rozwiń"}<ChevronDown/></span>
    </button>
    <div className="mini-calendar-body">
      <div className="mini-calendar-grid">{["P","W","Ś","C","P","S","N"].map((d,i)=><small key={`${d}${i}`}>{d}</small>)}{cells.map((day,i)=>day?<button type="button" className={`${day===now.getDate()?"today ":""}${day===selectedDay?"selected":""}`} key={i} onClick={()=>setSelectedDay(day)}><b>{day}</b>{(tasks.some(t=>!!t.deadline&&localDay(new Date(t.deadline))===date(day))||subjects.some(s=>s.exam_date===date(day)))&&<em/>}</button>:<i key={i}/>)}</div>
      <div className="calendar-day-details"><div className="selected-day-head"><div><span className="kicker">WYBRANY DZIEŃ</span><strong>{new Intl.DateTimeFormat("pl-PL",{weekday:"long",day:"numeric",month:"long"}).format(new Date(now.getFullYear(),now.getMonth(),selectedDay))}</strong></div><button type="button" onClick={()=>addTask(selectedDate)}><CirclePlus/>Dodaj zadanie</button></div>{!selectedTasks.length&&!selectedExams.length?<p>Na ten dzień nic nie zaplanowano.</p>:<div>{selectedTasks.map(task=><button key={task.task_uid} onClick={()=>openTask(task)}><span className={`event-dot ${task.priority.toLowerCase()}`}/><div><strong>{task.title}</strong><small>{task.deadline?new Intl.DateTimeFormat("pl-PL",{hour:"2-digit",minute:"2-digit"}).format(new Date(task.deadline)):""} · zadanie</small></div><ChevronRight/></button>)}{selectedExams.map(subject=><article key={subject.subject_uid}><span className="event-dot exam"/><div><strong>{subject.name}</strong><small>Egzamin</small></div></article>)}</div>}</div>
    </div>
    <div className="calendar-agenda"><span className="kicker">NAJBLIŻSZE TERMINY</span>{!upcoming.length&&!exams.length?<p className="agenda-empty">Brak nadchodzących terminów.</p>:<>{upcoming.map(task=><button key={task.task_uid} onClick={()=>openTask(task)}><span className={`agenda-date ${task.priority.toLowerCase()}`}><b>{new Date(task.deadline!).getDate()}</b><small>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(task.deadline!))}</small></span><div><strong>{task.title}</strong><small>{new Intl.DateTimeFormat("pl-PL",{weekday:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(task.deadline!))} · zadanie</small></div><ChevronRight/></button>)}{exams.map(subject=><div className="agenda-exam" key={subject.subject_uid}><span className="agenda-date exam"><b>{new Date(`${subject.exam_date}T12:00`).getDate()}</b><small>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(`${subject.exam_date}T12:00`))}</small></span><div><strong>{subject.name}</strong><small>Egzamin</small></div></div>)}</>}</div>
    <button type="button" className="calendar-open" onClick={open}>Otwórz pełny kalendarz <ChevronRight/></button>
  </section>
}
function Onboarding({title,text,action,click}:{title:string;text:string;action:string;click:()=>void}) { return <div className="onboarding"><span><Sparkles /></span><h2>{title}</h2><p>{text}</p><button className="primary" onClick={click}><CirclePlus />{action}</button></div>; }
function TaskList({ tasks, topicName, toggle, remove, open, edit,duplicate,selected,onSelect }: { tasks: Task[]; topicName: (id:string)=>string; toggle:(t:Task)=>void; remove:(id:string)=>void; open?:(t:Task)=>void; edit?:(t:Task)=>void;duplicate?:(t:Task)=>void;selected?:Set<string>;onSelect?:(id:string)=>void }) {
  if (!tasks.length) return <Empty text="Tu jest czysto. Dobra robota!" />;
  return <div className="task-list">{tasks.map(task => <article className={task.is_done ? "task done" : "task"} key={task.task_uid}>{onSelect?<input className="bulk-check" type="checkbox" checked={selected?.has(task.task_uid)??false} onChange={()=>onSelect(task.task_uid)} aria-label={`Zaznacz ${task.title}`}/>:<button className="check" onClick={() => toggle(task)} aria-label={task.is_done?"Oznacz jako niewykonane":"Oznacz jako wykonane"}>{task.is_done && <Check />}</button>}<button className="task-main" onClick={()=>open?.(task)}><strong>{task.title}</strong><span>{topicName(task.topic_uid)} · {fmtDate(task.deadline)}</span>{task.notes&&<small className="task-note">{task.notes}</small>}</button><i className={`priority ${task.priority.toLowerCase()}`}>{task.priority === "HIGH" ? "Wysoki" : task.priority === "LOW" ? "Niski" : "Średni"}</i><span className="row-actions">{duplicate&&<button className="icon" onClick={()=>duplicate(task)} title="Duplikuj zadanie"><Copy size={16}/></button>}{edit && <button className="icon" onClick={() => edit(task)} title="Edytuj zadanie"><Pencil /></button>}<button className="icon trash" onClick={() => remove(task.task_uid)} title="Usuń zadanie"><Trash2 /></button></span></article>)}</div>;
}

function TaskSessionNotes({sessions,openSession}:{sessions:Session[];openSession:(session:Session)=>void}) {
  const noted=sessions.filter(session=>session.notes?.trim()).sort((a,b)=>new Date(b.started_at).getTime()-new Date(a.started_at).getTime());
  return <section className="task-session-notes"><div className="panel-head"><div><span className="kicker">NOTATKI</span><h3>Notatki z sesji nauki</h3></div><span className="session-note-count"><BookOpen/>{noted.length}</span></div>{noted.length?<div className="task-session-note-list">{noted.map(session=><button key={session.study_uid} onClick={()=>openSession(session)}><span className="session-note-date"><b>{new Date(session.started_at).getDate()}</b><small>{new Intl.DateTimeFormat("pl-PL",{month:"short"}).format(new Date(session.started_at))}</small></span><div><p>{session.notes}</p><small>{session.duration_minutes??0} min nauki · kliknij, aby otworzyć sesję</small></div><ChevronRight/></button>)}</div>:<div className="task-session-notes-empty"><BookOpen/><p>To miejsce jest przeznaczone na notatki z sesji nauki.</p><small>Dodaj notatkę podczas zapisywania lub edycji sesji przypisanej do tego zadania.</small></div>}</section>
}

export default App;
